### ISSUE TITLE
Eastern Hemisphere Townhall Meeting #18 - 15th Jan 2022 0800 to 1000

### ISSUE THREAD

**Issue by wolstaeb** [C3ETH/c3eth-operations#109]
- Last Meeting: #95 
- Next Meeting: 

- **[Meeting Link](https://www.meetup.com/Cardano-Catalyst-Community-Network/events/cnlrqsydccbtb/)**
- **[Opening Presentation](https://docs.google.com/presentation/d/1l1PMDVZY9nmvIo_xmbuVhQy736QcW6Lq/edit?usp=sharing&ouid=110227914279933022424&rtpof=true&sd=true)**

## Meeting Soundbite

[**TO BE DONE**]: fill out after the meeting. Please see [Breakout Room Summaries below](#breakout-room-summaries)

## Breakout Rooms

0. Welcome
1. Japanese
2. Indonesian 
3. English / Eastern Africa
4. Vietnamese

## Run sheet

1. Welcome
2. Overview of Catalyst (Catalyst Clock)
3. Breakout Rooms

## Attendees

EHT # | Date | Participants | Japan | Indonesia | Vietnam | English | Korean | Catalyst School
-- | -- | -- | -- | -- | -- | -- | -- | --
1 | 29/07/2021 | 47 | 15 | 14 | 5 | 7 | - | -
2 | 05/08/2021 | 64 | 11 | 11 | 32 | 12 | - | -
3 | 12/08/2021 | 93 | 43 | 10 | 29 | 11 | - | -
4 | 19/08/2021 | 94 | 49 | 3 | 19 | 11 | - | 12
5 | 26/08/2021 | 62 | 35 | 7 | 10 | 10 | - | -
6 | 02/09/2021 | 76 | 31 | 6 | 22 | 14 | - | 3
7 | 09/09/2021 | 95 | 39 | 9 | 30 | 7 | 4 | 6
8 | 18/09/2021 | 95 | 39 | 8 | 31 | 7 | 4 | 6
9 | 25/09/2021 | 72 | 25 | 8 | 24 | 12 | 3 | -
10 | 02/10/2021 | 85 | 40 | 11 | 22 | 8 | 4 | -
11 | 9/10/2021 | 47 | 26 | 10 | 3 | 8 | - | -
12 | 16/10/2021 | 69 | 21 | - | 41 | 5 | 2 | -
13 | 23/10/2021 |48 | 16 | 3 | 11 | 8 | - | -
14 | 06/11/2021 |- | - | - | 9  | - | - | -
15 | 06/11/2021 | 68 | 25 | 4 | 14 | 20 | - | 5
16 | 04/12/2021 |- | - | - | -  | - | - | -
17 | 18/12/2021 |- | - | - | -  | 14 | - | -
18 | 18/12/2021 |- | - | 11 | 11  | 15 | - | -

## Hosts

Hosts, please arrive 30mins before the start of the Townhall to make last-minute adjustments to the schedule and go over the run sheet.

- Mie Tran (@Mietran0407) - VN
- Robert O'Brien  (@wolstaeb) - EN
- Tien Nguyen Anh (@tienna) 
- Angela Gatende (@A-W-G) - EN
- Felix Weber (@FelixfromSwarm) - EN 
- Andreas Sosilo (@andreassosilo) - IN
- Linh LP - VN/EN
- Andre Chyadi
- Ayu Kusummaningtyas
- Yuta Yuta (@cardanoz) - JP

### Indonesian

Indonesian break out room has 18 people attending. We have AMA (Ask Me Anything) event today about governance in Cardano & Project Catalyst. And giving rewards to 5 best question to the participants.

#### Our discussions

Introduction to Project Catalyst
What is IdeaScale?
Fund cycle
Catalyst Voting apps
How to use CA tools
Q&A

### Japan

[**TO BE DONE**]: fill out after the meeting. 

### Vietnam

Today's Vietnam town hall meeting has 11 people attending. We wrap up 2021's achievements, introducing Gitlocalize and having some sharings and comments of current Cardano's activities and schedule.

### English

What *is* Catalyst to you? How does voting work, what does *good* mean, and how can we, should we enrich Catalyst with the voices of more women? These were these themes of discussion in the English breakout room. Approximately fifteen people joined in a two-hour discussion that contributed to forming a sense of what is Catalyst and what it represents. The question was asked by new participants to Catalyst and the Eastern Townhall. The answers were full of insight and great perspectives. Thank you to everyone for participating.

#### Related Links
- [Empowering Women through Cardano](https://cardano.ideascale.com/c/idea/381933)
- [Boosting Diversity in Catalyst](https://cardano.ideascale.com/c/idea/384803)
- [Github Global Diversity](https://github.com/about/diversity)

## Eastern Town Hall Social Media Links
 
- Meetup: https://www.meetup.com/Cardano-Catalyst-Community-Network/
- Telegram: https://t.me/joinchat/ODKTOvGnrHEwNTc6
- Discord: https://discord.gg/6T825EyvrG
- Email: eastern.townhall@gmail.com

**Comment by Mietran0407** [comment]
Today's Vietnam town hall meeting has 11 people attending. We wrap up 2021's achievements, introducing Gitlocalize and having some sharings and comments of current Cardano's activities and schedule.

**Comment by andreassosilo** [comment]
Indonesian break out room has 14 people attending. We have AMA (Ask Me Anything) event today about governance in Cardano & Project Catalyst. And giving rewards to 5 best question to the participants.

**Our discussions:**

- Introduction to Project Catalyst
- What is IdeaScale?
- Fund cycle
- Catalyst Voting apps
- How to use CA tools
- Q&A
