### ISSUE TITLE
Catalyst Reporting [KPI] Reports covering 25 Dec 2021 - 25 Jan 2022

### ISSUE THREAD

**Issue by PardusEidolon** [C3ETH/c3eth-operations#113]
### Proposals for Fund 6

- [x] [Connecting Asian Voters Proposers](https://cardano.ideascale.com/a/dtd/Connecting-Asian-Voters-Proposers/369063-48088)
- [x]  [Eastern TownHall Team Operation](https://cardano.ideascale.com/a/dtd/Eastern-TownHall-Team-Operation/369124-48088)
- [x] [Connect East Asian Entrepreneurs](https://cardano.ideascale.com/a/dtd/Connect-East-Asian-Entrepreneurs/369120-48088)
- [x] [On-boarding East Asia Today!](https://cardano.ideascale.com/a/dtd/368844-48088)

Please refer to [Orbit.Love](https://app.orbit.love/c3eth), [Cauldron for Activity Reporting]( https://cauldron.io/project/5314), and our [spreadsheet summerising the data for the last 30 days](https://docs.google.com/spreadsheets/d/1TmSZ7ngSFcrML6wjrKJrW6ISYNQV2wymU4ZsNC7M08o/edit?usp=sharing).

### Details about our Metrics

We are basing our primary metric on community activity using the Orbit Gravity [1]  (KPI1) metric to measure CHAOSS Project Popularity (which measures community interactions/value). We are only getting the setup at the moment.  Team contributions will be measured according to Orbit Love[1] (KPI2) and codification of contributions will follow the Community Engagement Framework [3]. For the moment we are reporting across all C3ETH repositories because we are still figuring out how to organise our work.

Tracking progress toward deliverables will use Github Closed Issues (KPI3) as the metric for CHAOSS Project Velocity [2]. We are using Github Issues and Project Boards to track project tasks/activity of the team and also to help with collaboration outside of the team. Closed issues measure our inputs into the project.  

Community activity is measured using the Orbit Gravity [2] metric to measure CHAOSS Project Popularity (which measures community interactions/value). Contributions toward this metric will follow the Community Engagement Framework [3]. Specific activity types and weights are being developed. 

We’ve switched to using Orbit Gravity instead of Orbit Presence to measure community health. After experience using Orbit Love Ecosystem Tool, Gravity better reflects our objective and is easier to calculate.

We are still setting up our reporting system. Our gravity metric does not include a lot of activity prior to fund 7 or telegram which is used heavily in Vietnam and Indonesia.
KPI Calculations can be found in ETH-KPI-Fund6-Dec2021 spreadsheet [5]

[1] https://github.com/orbit-love/orbit-model
[2]  https://communityroundtable.com/best-practices/thecrs-work-out-loud-framework/
[3] https://chaoss.community/
[4] https://cauldron.io/project/5314
[5] https://docs.google.com/spreadsheets/d/1TmSZ7ngSFcrML6wjrKJrW6ISYNQV2wymU4ZsNC7M08o/edit?usp=sharing

**Comment by wolstaeb** [comment]
@Mietran0407 @PardusEidolon  worked through with @wolstaeb how to do the KPI reporting. Learning about Orbit and Cauldron for reporting purposes. Bravo!
