### ISSUE TITLE
Event [Townhall]: Eastern Hemisphere Townhall Event #19 - 29 JAN 2022 0900 to 11:00 UTC

### ISSUE THREAD

**Issue by wolstaeb** [C3ETH/c3eth-operations#117]
Register for [Eastern Townhall Events](https://bit.ly/3H9Xvoo) via the Cardano and Catalyst Community Network on meetup.com. 

- [Meeting Link](https://zoom.us/meeting/register/tJIrcumprTssEtN_RkkiNfKkyWmKn2G65mX3)
- [Openning Presentation]()

- Last Meeting: #109 
- Next Meeting:  #122 
## Meeting Soundbite

[**TO BE DONE**]: fill out after the meeting. Please see [Breakout Room Summaries below](#breakout-room-summaries)

## Breakout Rooms

For this Eastern Townhall we are running a mini Ideafest in the main room. In English. The aim is to enable proposers in our community to connect with voters. Each proposer gets 2 mins to pitch their proposals (NO Slides only your IdeaScale proposal(s) are shown) in a group of three. Then the audience can ask questions. Repeat for the next three. 

If there is time and audience participation we can break out into our normal breakroom formats. Perhaps allowing non-English speaking proposers and audiences a chance to hear the proposers again in their native language. 

1. Japanese
2. Indonesian
3. English / Eastern Africa
4. Vietnamese
5. Korean

## Run sheet

1. Welcome
2. Mini Ideafest Introduction
3. Proposer Group - Presenting/Q&A
4. Breakout Rooms (optional)

The list of [proposers that pitched](https://docs.google.com/spreadsheets/d/15Ck-lnUbscOu1oj58CGU6-3ssWftadWUHP9_L4CElg4/edit?usp=sharing) and [their proposals in the voter tool](https://cardanocataly.st/voter-tool/#/f7/picked). Don't forget the [Challenge setting proposals too](https://cardanocataly.st/voter-tool/#/f7/shared/27339ab8-d6b3-413e-91e3-dffcc8f5765f). 

## Attendee Numbers

EHT # | Date | Participants | Japan | Indonesia | Vietnam | English | Korean | Catalyst School
-- | -- | -- | -- | -- | -- | -- | -- | --
19 | 29.01.2022 | 54 | -- | -- | -- | 22 | -- | --

## Meeting Soundbite

[**TO BE DONE**]: fill out after the meeting. Please see [Breakout Room Summaries below](#breakout-room-summaries)
## Hosts

Hosts, please arrive 30mins before the start of the Townhall to make last-minute adjustments to the schedule and go over the run sheet.

- Yuta Yuta (@cardanoz)
- Mie Tran (@Mietran0407)
- Linh (@Linh-LP)
- Tien Nguyen Anh (@tienna)
- Andreas Sosilo (@andreassosilo) 
- Andy Sibuea (@zicozibu)
- Yan Tirta (@YanTirta)
- Angela Gatende (@A-W-G)
- Robert O'Brien (@wolstaeb)
- Felix Weber (@FelixfromSwarm)
- Andre Chyadi

### Indonesian

The Indonesian community presented our Cardano Indonesia proposals during "Mini IdeaFest" in the main room. Instead of an Indonesian breakout room for this meetup, we joined the English breakout room. For the next meetup, we will have a workshop "Introduction to Catalyst" and/or "How to become CA". This is preparation for the next Fund 8.
 
### Japan

[**TO BE DONE**]: fill out after the meeting. 

### Vietnam

[**TO BE DONE**]: fill out after the meeting. 

### English

After a great mini Ideafest in the main room, we had a short English breakout room. We got a run down from Vinay about the [Konma and their Fund 7 proposals](https://linktr.ee/KonmaCatalystFund7). Then we got into a great conversation about No-code and Low-Code environments with Andrew Forson and Tim O'Brien. As a result, we plan to do a No-Code bake-off session in a future Eastern-Townhall.

## Eastern Town Hall Social Media Links
 
- Meetup: [Eastern Townhall Events](https://bit.ly/3H9Xvoo)
- Telegram: https://bit.ly/3H6nEo2
- Discord: https://bit.ly/3r0PP21
- Twitter: https://bit.ly/3u4EOhZ
- Email: [eastern.townhall@gmail.com](mailto:eastern.townhall@gmail.com)

**Comment by andreassosilo** [comment]
From Indonesian community, we don't have Indonesian breakout room for this meetup. We presented our Cardano Indonesia proposals during "Mini IdeaFest" in the main room. And then we joined the English breakout room.

For the next meetup, we will have workshop "Introduction to Catalyst" and/or "How to become CA". This is preparation for the next Fund 8.
