### ISSUE TITLE
Update the Zoom link for Eastern Town Hall Meetup

### ISSUE THREAD

**Issue by andreassosilo** [C3ETH/c3eth-operations#119]
**Tasks:**

- [x] Request the new Zoom link for bi-weekly meeting
- [x] Add that Zoom link in the Meetup event for Eastern Town Hall Meetup
- [x] Test & check

**Comment by wolstaeb** [comment]
Here is the [Meeting Link]( https://us02web.zoom.us/meeting/register/tZcqcOCopjsuGNd0IAZPoGfYNEYCXO_prtEd). 

That is the link for reoccurring Town Halls. Currently, the settings on the meeting mean everyone must register each time. In addition to the Meetup page, I think we should have a page on our website which describes the event and provides links to the calendar and meeting links.
