### ISSUE TITLE
Event [Townhall]: Eastern Hemisphere Townhall Event #20 - 12th Feb 2022 0900 to 11:00 UTC

### ISSUE THREAD

**Issue by wolstaeb** [C3ETH/c3eth-operations#122]
Register for [Eastern Townhall Events](https://bit.ly/3H9Xvoo) via the Cardano and Catalyst Community Network on meetup.com. 

- [Zoom Meeting Link](https://zoom.us/meeting/register/tJIrcumprTssEtN_RkkiNfKkyWmKn2G65mX3)
- [Openning Presentation](https://docs.google.com/presentation/d/1vc_LPtPtvfUzQ-ljdMhpdjPApRkMTNBA/edit)
- [Project Catalyst Survey](https://docs.google.com/forms/d/e/1FAIpQLSdvvvD-TmgNd4OdWhkke7ZTZDG-fmFStr961IdwZY5MDiQGNA/viewform)
- [Eastern Townhall Community Calendar](https://calendar.google.com/calendar/embed?src=kg3go90c7fu4jr1fsqk00h43b4%40group.calendar.google.com&ctz=Etc%2FGMT)

- Last Meeting:  #117 
- Next Meeting: #127 

## Meeting Soundbite

[**TO BE DONE**]: fill out after the meeting. Please see [Breakout Room Summaries below](#breakout-room-summaries)

## Breakout Rooms

0. Welcome
1. Japanese
2. Indonesian
3. English / Eastern Africa
4. Vietnamese
5. Korean

## Run sheet

1. Welcome
2. (Programme Item)
3. Ideafest Intro
4. Breakout Rooms
## Attendee Numbers

EHT # | Date | Participants | Japan | Indonesia | Vietnam | English | Korean | Catalyst School
-- | -- | -- | -- | -- | -- | -- | -- | --
20 | 12.02.2022 | 61 | 10 | 22 | 24 | 5 | -- | --

## Meeting Soundbite

[**TO BE DONE**]: fill out after the meeting. Please see [Breakout Room Summaries below](#breakout-room-summaries)
## Hosts

Hosts, please arrive 30mins before the start of the Townhall to make last-minute adjustments to the schedule and go over the run sheet.

- Yuta Yuta (@cardanoz)
- Linh (@Linh-LP)
- Tien Nguyen Anh (@tienna)
- Andreas Sosilo (@andreassosilo) 
- Andre Chyadi
- Ayu Kusummaningtyas
- Andy Sibuea (@zicozibu)
- Yan Tirta (@YanTirta)
- Angela Gatende (@A-W-G)
- Robert O'Brien (@wolstaeb)

## Appologies

- Mie Tran (@Mietran0407)

## Fund 7 Eastern Townhall Funded Proposals

- [Eastern Town Hall](https://cardano.ideascale.com/a/dtd/Eastern-Town-Hall/381931-48088?submitted=1)
- [Eastern Town Hall Language Support](https://cardano.ideascale.com/a/dtd/Eastern-Town-Hall-Language-Support/383404-48088)
- [Eastern Town Hall & Japan](https://cardano.ideascale.com/a/dtd/Eastern-Town-Hall-Japan/383409-48088?submitted=1)
- [Eastern Town Hall Challenge](https://cardano.ideascale.com/a/dtd/Grow-East-Asia-Grow-Cardano/382067-48088)

## Fund 8 Challenges
[Developer Ecosystem](https://cardano.ideascale.com/c/idea/384822)
[Open Source Development Ecosystem](https://cardano.ideascale.com/c/idea/382213)
[Nation Building Dapps](https://cardano.ideascale.com/c/idea/383828)
[Cross-Chain Collaboration](https://cardano.ideascale.com/c/idea/381705)
[Cardano scaling solutions](https://cardano.ideascale.com/c/idea/383094)
[DApps and Integrations](https://cardano.ideascale.com/c/idea/383335)
[Scale-UP Cardano's Community Hubs](https://cardano.ideascale.com/c/idea/381022)
[Gamers On - Chained](https://cardano.ideascale.com/c/idea/381329)
[Miscellaneous Challenge](https://cardano.ideascale.com/c/idea/381326)
[Grow Africa, Grow Cardano](https://cardano.ideascale.com/c/idea/384227)
[Accelerate Decentralized Identity](https://cardano.ideascale.com/c/idea/383978)
[Grow East Asia, Grow Cardano](https://cardano.ideascale.com/c/idea/382067)
[Business Solutions (B2B & B2C)](https://cardano.ideascale.com/c/idea/382660)
[Lobbying for favorable legislation](https://cardano.ideascale.com/c/idea/381094)
[Improve and Grow Auditability](https://cardano.ideascale.com/c/idea/383480)
[The Great Migration (from Ethereum)](https://cardano.ideascale.com/c/idea/382642)
[Open Standards & Interoperability](https://cardano.ideascale.com/c/idea/383619)
[New Member Onboarding](https://cardano.ideascale.com/c/idea/382639)
[Self-Sovereign Identity](https://cardano.ideascale.com/c/idea/380986)
[Film + Media (FAM) creatives unite!](https://cardano.ideascale.com/c/idea/383633)
[Community Advisor Improvements](https://cardano.ideascale.com/c/idea/384394)
[Grow India, Grow Cardano](https://cardano.ideascale.com/c/idea/381216)

### Indonesia
**Recap from Indonesia Breakout Room:**
- Topics: Introduction to Catalyst, Eastern Town Hall & IOG, Sharing Experience as CA in Fund 7
- Moderator: @YanTirta 
- Speakers: @andreassosilo , @andrecahyadi , Dani & Syarbel
- Total participants: 22 persons
- Duration: 2 hours
- Q&A session with 500,000 IDR as total rewards for 5 best questions from participants (will be paid in ADA)
- Explanation on how to use IdeaScale & Catalyst Voting App
- Introduce Cardano Indonesia social media to newcomers
- Introduce Project Catalyst in general + schedule for Fund 8

### Japan

[**TO BE DONE**]: fill out after the meeting. 
### Vietnam
Published recording [https://youtu.be/OyFSAS0iYKw](https://youtu.be/OyFSAS0iYKw)
Slides used [https://docs.google.com/presentation/d/14re_9_wSl5F5stExoVhwCUlt9RhTpC6s/edit?usp=sharing&ouid=101771009461790797959&rtpof=true&sd=true](https://docs.google.com/presentation/d/14re_9_wSl5F5stExoVhwCUlt9RhTpC6s/edit?usp=sharing&ouid=101771009461790797959&rtpof=true&sd=true)
### Korea

[**TO BE DONE**]: fill out after the meeting. 
### English

[**TO BE DONE**]: fill out after the meeting. 

## Eastern Town Hall Social Media Links
 
- Meetup: [Eastern Townhall Events](https://bit.ly/3H9Xvoo)
- Zoom: [Meeting Link](https://zoom.us/meeting/register/tJIrcumprTssEtN_RkkiNfKkyWmKn2G65mX3)
- Calendar: [Community Calendar](https://calendar.google.com/calendar/embed?src=kg3go90c7fu4jr1fsqk00h43b4%40group.calendar.google.com&ctz=Etc%2FGMT)
- Telegram: https://bit.ly/3H6nEo2
- Discord: https://bit.ly/3r0PP21
- Twitter: https://bit.ly/3u4EOhZ
- Email: [eastern.townhall@gmail.com](mailto:eastern.townhall@gmail.com)

**Comment by andreassosilo** [comment]
**Recap from Indonesia Breakout Room:**
- Topics: Introduction to Catalyst, Eastern Town Hall & IOG, Sharing Experience as CA in Fund 7
- Moderator: @YanTirta 
- Speakers: @andreassosilo , @andrecahyadi , Dani & Syarbel
- Total participants: 22 persons
- Duration: 2 hours
- Q&A session with 500,000 IDR as total rewards for 5 best questions from participants (will be paid in ADA)
- Explanation on how to use IdeaScale & Catalyst Voting App
- Introduce Cardano Indonesia social media to newcomers
- Introduce Project Catalyst in general + schedule for Fund 8
