### ISSUE TITLE
Meeting [Team Checkin]: Core Team Weekly 14th 02 2022 - 0800 to 1000 UTC

### ISSUE THREAD

**Issue by wolstaeb** [C3ETH/c3eth-operations#123]
- [Meeting Link](https://us02web.zoom.us/j/89664896982?pwd=RDlQNDRYTlZFZWVDWklvcXBqeFM0UT09): One-Time Registration is required. 
- Last Meeting: #121 
- Next Meeting: #124 
- [C3ETH Team Calendar](https://calendar.google.com/calendar/embed?src=2g3h5vj0cui84imibn6bpa4tr4%40group.calendar.google.com&ctz=Etc%2FGMT)
- [Eastern Townhall Community Calendar](https://calendar.google.com/calendar/embed?src=kg3go90c7fu4jr1fsqk00h43b4%40group.calendar.google.com&ctz=Etc%2FGMT)

### Attendees

- Yuta Yuta (@cardanoz)
- Mie Tran (@Mietran0407)
- Linh (@Linh-LP)
- Andreas Sosilo (@andreassosilo) 
- Andy Sibuea (@zicozibu)
- Yan Tirta (@YanTirta)
- Angela Gatende (@A-W-G)
- Robert O'Brien (@wolstaeb)
- Jack O'Brien (@PardusEidolon)
- Andre Cahyadi (@andrecahyadi)

### Topics to cover

1. General catch-up with each other.
2. Review of Weekends Townhall
3. Catalyst Updates (if any)
4. Outstanding Points from #121 
5. Review of Funded C3ETH Fund 7 Proposals
6. Fund 8 Challenge Translation (@wolstaeb)
7. Three Month Milestones (@wolstaeb)
8. Fund 8 Proposal Team 
9. Mini Challenge Fest Idea (@wolstaeb) 
10. Compensation for Feb 2022 (@wolstaeb)

### Notes and Followups from #121 

- [x] Orbit & KPI Reporting - Ecosystem CRM & Privacy
- [x] C3ETH Meetup & Zoom Registration
- [x] Community Translation
- [x] Working sessions for Orbit & Closeout/Retrospective - @wolstaeb still behind.
- [x] Working Group Setup for Catalyst Innovate
- [x] Translation Compensation
- [x] Member Survey
- [x] Mini Idea Fest Name & Format
- [x] Promoting C3ETH Stakepool and [Ryuuki Network](https://catalystswarm.com/pool-network/)
- [x] Fund 8 Challenge Setting Reviews (Video like Yuta Proposal Reviews)
- [x] Eastern Town Hall Ideas Funding

## Fund 7 Eastern Townhall Funded Proposals

- [Eastern Town Hall](https://cardano.ideascale.com/a/dtd/Eastern-Town-Hall/381931-48088?submitted=1)
- [Eastern Town Hall Language Support](https://cardano.ideascale.com/a/dtd/Eastern-Town-Hall-Language-Support/383404-48088)
- [Eastern Town Hall & Japan](https://cardano.ideascale.com/a/dtd/Eastern-Town-Hall-Japan/383409-48088?submitted=1)
- [Eastern Town Hall Challenge](https://cardano.ideascale.com/a/dtd/Grow-East-Asia-Grow-Cardano/382067-48088)

**Comment by andrecahyadi** [comment]
Some of my notes from today's meeting:

Everyone: 
- IdeaFest Reels is the new name for Mini IdeaFest 
- The IdeaFest Reels will be also presented inside breakout rooms using local languages

Robert:
- Knowledge sharing session with proposers -> Writing Tips: Title; Problem; Solution
- Orbit & KPI reporting -> there's some disturbing privacy information 

Andreas:
- Propose knowledge sharing session with proposers with the help from Catalyst School
- Ask about Member Survey activities

Linh:
- Propose a deadline by end of Feb 2022 to translate all Fund 8 categories
- Agree to become a Challenge Team for Grow East Asia Grow Cardano Fund 8 challenge

Yan:
- Will give updates regarding translation for all Fund 8 categories:
a. Calculate total wordings for all Fund 8 categories 
b. The amount available & payment structure 
- Agree to become a Challenge Team for Grow East Asia Grow Cardano Fund 8 challenge

Andre:
- Is the Fund 8 categories' translation will be using the budget from Eastern Town Hall Language Support funded proposal? What's the relation with only 1,000 ADA available funds?
