### ISSUE TITLE
Event [Townhall]: Eastern Hemisphere Townhall Event #21 - 26 Feb 2022 0900 to 11:00 UTC

### ISSUE THREAD

**Issue by wolstaeb** [C3ETH/c3eth-operations#127]
Register for [Eastern Townhall Events](https://bit.ly/3H9Xvoo) via the Cardano and Catalyst Community Network on meetup.com. 

- [Meeting Link](https://zoom.us/meeting/register/tJIrcumprTssEtN_RkkiNfKkyWmKn2G65mX3)
- [Openning Presentation](https://docs.google.com/presentation/d/1-ROvgd4upShdocn2A6CC6lzLp472eTpTUNibCMsPAKA/edit?usp=sharing)
- [Project Catalyst Survey](https://docs.google.com/forms/d/e/1FAIpQLSdvvvD-TmgNd4OdWhkke7ZTZDG-fmFStr961IdwZY5MDiQGNA/viewform)
- [Eastern Townhall Community Calendar](https://calendar.google.com/calendar/embed?src=kg3go90c7fu4jr1fsqk00h43b4%40group.calendar.google.com&ctz=Etc%2FGMT)

- Last Meeting: #122 
- Next Meeting: #132 

## Meeting Soundbite

The Eastern Town had fifty four participants across five rooms dicussing Fund 8 challenges and how to submit proposals.
In the Indonesian room we gave workshops about Fund 8 category challenges and also discuss on how to submit proposal via IdeaScale. In the English room there was small opportunity towork through the fund 8 challenges and how to thankin about proposal development. In the Vietnamese breakout room we shared and summarized the Fund8 Challenges and gave a basic how-to-write instructions. Across all the rooms we shared proposer insight.

## Breakout Rooms

0. Welcome
1. Japanese
2. Indonesian
3. English / Eastern Africa
4. Vietnamese
5. Catalyst School

## Run sheet

1. Welcome
2. Catalyst School
3. Challenge Reel (Introduction)
4. Breakout Rooms

## Attendee Numbers

EHT # | Date | Participants | Japan | Indonesia | Vietnam | English | Korean | Catalyst School
-- | -- | -- | -- | -- | -- | -- | -- | --
21 | 26.02.2022 | 54 | 10 | 25 | 14 | 3 | -- | 2

## Hosts

Hosts, please arrive 30mins before the start of the Townhall to make last-minute adjustments to the schedule and go over the run sheet.

- Yuta Yuta (@cardanoz)
- Mie Tran (@Mietran0407)
- Linh (@Linh-LP)
- Tien Nguyen Anh (@tienna)
- Andreas Sosilo (@andreassosilo) 
- Andre Chyadi
- Ayu Kusummaningtyas
- Andy Sibuea (@zicozibu)
- Yan Tirta (@YanTirta)
- Robert O'Brien (@wolstaeb)
- Seomon Blub (@Seomon4u)

## Appologies

- Angela Gatende (@A-W-G)

## Fund 8 Challenges

- [Developer Ecosystem](https://easterntownhall.com/catalyst/fund8/challenges/developer-ecosystem/campaign-brief/)
- [Open Source Development Ecosystem](https://easterntownhall.com/catalyst/fund8/challenges/open-source-development-ecosystem/campaign-brief/)
- [Nation Building Dapps](https://easterntownhall.com/catalyst/fund8/challenges/nation-buidling-daaps/campaign-brief/)
- [Cross-Chain Collaboration](https://easterntownhall.com/catalyst/fund8/challenges/cross-chain-collaboration/campaign-brief/)
- [Cardano scaling solutions](https://easterntownhall.com/catalyst/fund8/challenges/cardano-scaling-solutions-/campaign-brief/)
- [DApps and Integrations](https://easterntownhall.com/catalyst/fund8/challenges/dapps-and-integrations/campaign-brief/)
- [Scale-UP Cardano's Community Hubs](https://easterntownhall.com/catalyst/fund8/challenges/scale-up-cardanos-community-hubs/campaign-brief/)
- [Gamers On - Chained](https://easterntownhall.com/catalyst/fund8/challenges/gamers-on-chained/campaign-brief/)
- [Miscellaneous Challenge](https://easterntownhall.com/catalyst/fund8/challenges/miscellaneous-challenge/campaign-brief/)
- [Grow Africa, Grow Cardano](https://easterntownhall.com/catalyst/fund8/challenges/grow-africa-grow-cardano/campaign-brief/)
- [Accelerate Decentralized Identity](https://easterntownhall.com/catalyst/fund8/challenges/accelerate-decentralized-idenity/campaign-brief/)
- [Grow East Asia, Grow Cardano](https://easterntownhall.com/catalyst/fund8/challenges/grow-east-asia-grow-cardano/campaign-brief/)
- [Business Solutions (B2B & B2C)](https://easterntownhall.com/catalyst/fund8/challenges/business-solutions-b2b-b2c/campaign-brief/)
- [Lobbying for favorable legislation](https://easterntownhall.com/catalyst/fund8/challenges/lobbying-for-favorable-legislation/campaign-brief/)
- [Improve and Grow Auditability](https://easterntownhall.com/catalyst/fund8/challenges/improve-and-grow-auditbility/campaign-brief/)
- [The Great Migration (from Ethereum)](https://easterntownhall.com/catalyst/fund8/challenges/the-great-migration-from-ethereum/campaign-brief/)
- [Open Standards & Interoperability](https://easterntownhall.com/catalyst/fund8/challenges/open-standards-and-interoperability/campaign-brief/)
- [New Member Onboarding](https://easterntownhall.com/catalyst/fund8/challenges/new-member-onboarding/campaign-brief/)
- [Self-Sovereign Identity](https://easterntownhall.com/catalyst/fund8/challenges/self-sovereign-identity/campaign-brief/)
- [Film + Media (FAM) creatives unite!](https://easterntownhall.com/catalyst/fund8/challenges/film-and-media-creatives-unite/campaign-brief/)
- [Community Advisor Improvements](https://easterntownhall.com/catalyst/fund8/challenges/community-advisor-improvements/campaign-brief/)
- [Grow India, Grow Cardano](https://easterntownhall.com/catalyst/fund8/challenges/grow-india-grow-cardano/campaign-brief/)

### Indonesian

Today we have 25 participants in Indonesia break out room. We gave workshops about Fund 8 category challenges and what is Cardano and Eastern Town Hall. We also discuss on how to submit proposal via IdeaScale.

[Further summary](https://forum.cardano.org/t/eastern-town-hall-indonesia-meetup-how-to-submit-proposal-in-fund-8-26-feb-2022/96553)

### Japan

Summary of events and questions from the [Japanese room](https://forum.cardano.org/t/2022-02-06/96538)

### Vietnam

Today's Vietnamese breakout room has 14 members attended, we shared and summarized the Fund8 Challenge Setting based on Robert's Slide and also show the community how to place là "place holder" on Ideascale with basic how-to-write instruction. There are insight sharings with proposers in the last 30 minutes.

### English

A small breakout room this week but a great opportunity to more closely work through the challenges for Fund 8 to help develop fundable proposals. It was genuinely a great session.

- [Challenge Reel Slides](https://docs.google.com/presentation/d/1q6Ydi6uar29UyAFPuyGuv6nStPHaSqsn9-8iF8e2PHQ/edit?usp=sharing)

## Eastern Town Hall Social Media Links
 
- Meetup: [Eastern Townhall Events](https://bit.ly/3H9Xvoo)
- [Zoom](https://zoom.us/meeting/register/tJIrcumprTssEtN_RkkiNfKkyWmKn2G65mX3)
- Telegram: https://bit.ly/3H6nEo2
- Discord: https://bit.ly/3r0PP21
- Twitter: https://bit.ly/3u4EOhZ
- Email: [eastern.townhall@gmail.com](mailto:eastern.townhall@gmail.com)

**Comment by andreassosilo** [comment]
Eastern Town Hall Indonesia

![flyerEHTIndo26022022](https://user-images.githubusercontent.com/50327438/155843055-0e3f1118-44f0-4d36-852f-16c024902087.jpg)

Topic: AMA - How to propose in Fund 8
Duration: 2 hours

Speakers: @andreassosilo @YanTirta @zicozibu , Dani, Syarbel
Moderator: Ayu

Today we have 25 participants in Indonesia break out room. We gave workshops about Fund 8 category challenges and what is Cardano and Eastern Town Hall. We also discuss on how to submit proposal via IdeaScale.

There is Q&A session in the last 45 mins.
