### ISSUE TITLE
Event [Townhall]: Eastern Hemisphere Townhall Event #22 - 12th March 2022 0900 to 11:00 UTC

### ISSUE THREAD

**Issue by wolstaeb** [C3ETH/c3eth-operations#132]
Register for [Eastern Townhall Events](https://bit.ly/3H9Xvoo) via the Cardano and Catalyst Community Network on meetup.com. 

- [Meeting Link](https://zoom.us/meeting/register/tJIrcumprTssEtN_RkkiNfKkyWmKn2G65mX3)
- [Openning Presentation](https://docs.google.com/presentation/d/10rlthAt0CG1HN4JM2IV6F0DDSl_D0eDcUmztjxt7oWo/edit?usp=sharing)
- [Project Catalyst Survey](https://docs.google.com/forms/d/e/1FAIpQLSdvvvD-TmgNd4OdWhkke7ZTZDG-fmFStr961IdwZY5MDiQGNA/viewform)
- [Eastern Townhall Community Calendar](https://calendar.google.com/calendar/embed?src=kg3go90c7fu4jr1fsqk00h43b4%40group.calendar.google.com&ctz=Etc%2FGMT)

- Last Meeting: #127 
- Next Meeting: #135 

## Meeting Soundbite

[**TO BE DONE**]: fill out after the meeting. Please see [Breakout Room Summaries below](#breakout-room-summaries)

## Breakout Rooms

0. Welcome
1. Japanese
2. Indonesian
3. English / Eastern Africa
4. Vietnamese
5. Catalyst School
6. Mini Proposal Workshop

## Run sheet

1. Welcome
2. Catalyst School - “How to become CA” 
3. Mini Proposal Workshop
4. Breakout Rooms

## Attendee Numbers

EHT # | Date | Participants | Japan | Indonesia | Vietnam | English | Korean | Mini Proposal
-- | -- | -- | -- | -- | -- | -- | -- | --
22 | 12.03.2022 | 78| 14 | 21 | 32 | 9 | -- | 2

## Meeting Soundbite

[**TO BE DONE**]: fill out after the meeting. Please see [Breakout Room Summaries below](#breakout-room-summaries)
## Hosts

Hosts, please arrive 30mins before the start of the Townhall to make last-minute adjustments to the schedule and go over the run sheet.

- Yuta Yuta (@cardanoz)
- Mie Tran (@Mietran0407)
- Linh (@Linh-LP)
- Tien Nguyen Anh (@tienna)
- Andreas Sosilo (@andreassosilo) 
- Ayu Kusummaningtyas
- Andy Sibuea (@zicozibu)
- Robert O'Brien (@wolstaeb)
- Angela Gatende (@A-W-G)
- Tevo Saks

### Appologies

- Yan Tirta (@YanTirta)

### Indonesian

We hosted the workshop divided into 5 sessions.  [@zicozibu](https://forum.cardano.org/u/zicozibu) covered about “What is Project Catalyst & Fund 8” , Then [@syarbel](https://forum.cardano.org/u/syarbel) gave presentation about being a CA. A Q&A session followed. [@CardanoToTheWorld](https://forum.cardano.org/u/cardanototheworld) explained how to write assessment as CA. Afterwards [@syarbel](https://forum.cardano.org/u/syarbel) walked through how to register in IdeaScale, and use CA Tools.
[Cardano Forum Summary](https://forum.cardano.org/t/eastern-town-hall-indonesia-meetup-how-to-become-ca-in-fund-8-12-mar-2022/97429)
 
### Vietnam

[**TO BE DONE**]: fill out after the meeting. 

### English

The English room was an open format driven by Q&As. We initially focused on a rundown of what is involved in being a CA. The discussion then focused on a problem, Coffee production in Eastern Africa, and how to structure the potential proposals. Finally, Dimitri, the General ADA holder representative, gave a rundown of the role and asked for feedback from the community.

### Mini Proposal Workshop
In these workshops, I let participants share their idea or problem statements and then refine a selected proposal.

## Catalyst School

These are the proposed Catalyst School workshop schedule:

- Saturday, 26 Feb 2022 -> Topic: “Proposing in Catalyst”
- Saturday, 12 Mar 2022  -> Topic:  “How to become CA” 
- Saturday, 26 Mar 2022 -> Topic:  “How to become vCA” Already informed also in the Catalyst School Discord Server

## Fund 8 Challenges

- [Developer Ecosystem](https://easterntownhall.com/catalyst/fund8/challenges/developer-ecosystem/campaign-brief/)
- [Open Source Development Ecosystem](https://easterntownhall.com/catalyst/fund8/challenges/open-source-development-ecosystem/campaign-brief/)
- [Nation Building Dapps](https://easterntownhall.com/catalyst/fund8/challenges/nation-buidling-daaps/campaign-brief/)
- [Cross-Chain Collaboration](https://easterntownhall.com/catalyst/fund8/challenges/cross-chain-collaboration/campaign-brief/)
- [Cardano scaling solutions](https://easterntownhall.com/catalyst/fund8/challenges/cardano-scaling-solutions-/campaign-brief/)
- [DApps and Integrations](https://easterntownhall.com/catalyst/fund8/challenges/dapps-and-integrations/campaign-brief/)
- [Scale-UP Cardano's Community Hubs](https://easterntownhall.com/catalyst/fund8/challenges/scale-up-cardanos-community-hubs/campaign-brief/)
- [Gamers On - Chained](https://easterntownhall.com/catalyst/fund8/challenges/gamers-on-chained/campaign-brief/)
- [Miscellaneous Challenge](https://easterntownhall.com/catalyst/fund8/challenges/miscellaneous-challenge/campaign-brief/)
- [Grow Africa, Grow Cardano](https://easterntownhall.com/catalyst/fund8/challenges/grow-africa-grow-cardano/campaign-brief/)
- [Accelerate Decentralized Identity](https://easterntownhall.com/catalyst/fund8/challenges/accelerate-decentralized-idenity/campaign-brief/)
- [Grow East Asia, Grow Cardano](https://easterntownhall.com/catalyst/fund8/challenges/grow-east-asia-grow-cardano/campaign-brief/)
- [Business Solutions (B2B & B2C)](https://easterntownhall.com/catalyst/fund8/challenges/business-solutions-b2b-b2c/campaign-brief/)
- [Lobbying for favorable legislation](https://easterntownhall.com/catalyst/fund8/challenges/lobbying-for-favorable-legislation/campaign-brief/)
- [Improve and Grow Auditability](https://easterntownhall.com/catalyst/fund8/challenges/improve-and-grow-auditbility/campaign-brief/)
- [The Great Migration (from Ethereum)](https://easterntownhall.com/catalyst/fund8/challenges/the-great-migration-from-ethereum/campaign-brief/)
- [Open Standards & Interoperability](https://easterntownhall.com/catalyst/fund8/challenges/open-standards-and-interoperability/campaign-brief/)
- [New Member Onboarding](https://easterntownhall.com/catalyst/fund8/challenges/new-member-onboarding/campaign-brief/)
- [Self-Sovereign Identity](https://easterntownhall.com/catalyst/fund8/challenges/self-sovereign-identity/campaign-brief/)
- [Film + Media (FAM) creatives unite!](https://easterntownhall.com/catalyst/fund8/challenges/film-and-media-creatives-unite/campaign-brief/)
- [Community Advisor Improvements](https://easterntownhall.com/catalyst/fund8/challenges/community-advisor-improvements/campaign-brief/)
- [Grow India, Grow Cardano](https://easterntownhall.com/catalyst/fund8/challenges/grow-india-grow-cardano/campaign-brief/)

## Eastern Town Hall Social Media Links
 
- Meetup: [Eastern Townhall Events](https://bit.ly/3H9Xvoo)
- [Zoom](https://zoom.us/meeting/register/tJIrcumprTssEtN_RkkiNfKkyWmKn2G65mX3)
- Telegram: https://bit.ly/3H6nEo2
- Discord: https://bit.ly/3r0PP21
- Twitter: https://bit.ly/3u4EOhZ
- Email: [eastern.townhall@gmail.com](mailto:eastern.townhall@gmail.com)

**Comment by andreassosilo** [comment]
**Recap Indonesia Break Out Room:**

For this meetup, we are having workshop "How to become CA in Fund 8"

Total participants: 20 persons

**Summary**
The event duration is 2 hours . We hosted the workshop online using Zoom . We divided the workshop into 5 sessions. The 1st session by [@zicozibu](https://forum.cardano.org/u/zicozibu) covered about “What is Project Catalyst & Fund 8” in the beginning.

Then in the 2nd session, [@syarbel](https://forum.cardano.org/u/syarbel) gave presentation about what is CA and how to register. After that we continued with Q&A session.

In 3rd session, [@CardanoToTheWorld](https://forum.cardano.org/u/cardanototheworld) gave explanation on how to write assessment as CA. And tips on how to check whether if a proposal pass the impact, feasibility, auditability.

Afterwards in 4th session, [@syarbel](https://forum.cardano.org/u/syarbel) gave hands-on on how to register in IdeaScale, and also how to use CA Tools that helps community advisor to do their work.

At the end of all session, we gave rewards for 5 best questions from participants.

We covered these topics during the workshop:

What is Project Catalyst
Catalyst Fund 8 Category Challenges
What is the role of Community Advisor
How to register as CA
CA guide
How to use CA Tools
Live Demo
Q&A
The next Eastern Town Hall Indonesia AMA will be held on Saturday, 26 March 2022 :pray:t2:

**Comment by whitevo** [comment]
**Mini Proposal Workshop Break-out Room**
In these workshops, I let participants share their idea or problem statements and then refine a selected proposal

Total Participants: 3

**Summary**
The event duration was 2 hours.
The edited version will be uploaded to the Swarm Youtube channel, but it will take a week or 2 until it's done.

In this session discussion, we picked up an existing proposal and came up with a problem statement "Cardano Ecosystem does not have bridges between already existing Decentralized Self Organizing movements"

Through ideation around the problem and solutions we finally settles on this solution:
"Establishing service to create, connect and maintain successful Decentralized Autonomous Organizations"

Miro Board we used for ideation: https://miro.com/app/board/uXjVOFkp8fQ=/

**Comment by Mietran0407** [comment]
**Vietnam Breakout Room**

In this workshop, we are having an AMA session " Fund8 CA What & How"

**Total participation: 35 people**

**Summary:** 

We created a pre-survey for the audience to submit questions, which we then address during the AMA session. Three Vietnamese guest speakers, all of whom are now vCAs, explained how to become a CA and vCA, why we need that position, what a filtered out assessment looks like, a challenge for a newbie to start, an example of how to write a good assessment, and how to break the language barrier for non-native English speakers.


The Youtube video recording: 
https://www.youtube.com/watch?v=Y8_AfOuSUjY&list=PLnMV9YICkyOU-OTB9odQCR0g98VDIROHB&index=10
