### ISSUE TITLE
Event [Townhall]: Eastern Hemisphere Townhall Event#23 - 26 March 2022 0900 to 11:00 UTC

### ISSUE THREAD

**Issue by wolstaeb** [C3ETH/c3eth-operations#135]
Register for [Eastern Townhall Events](https://bit.ly/3H9Xvoo) via the Cardano and Catalyst Community Network on meetup.com. 

- [Meeting Link](https://zoom.us/meeting/register/tJIrcumprTssEtN_RkkiNfKkyWmKn2G65mX3)
- [Openning Presentation](https://docs.google.com/presentation/d/10rlthAt0CG1HN4JM2IV6F0DDSl_D0eDcUmztjxt7oWo/edit?usp=sharing)
- [Project Catalyst Survey](https://docs.google.com/forms/d/e/1FAIpQLSdvvvD-TmgNd4OdWhkke7ZTZDG-fmFStr961IdwZY5MDiQGNA/viewform)
- [Eastern Townhall Community Calendar](https://calendar.google.com/calendar/embed?src=kg3go90c7fu4jr1fsqk00h43b4%40group.calendar.google.com&ctz=Etc%2FGMT)

- Last Meeting: #132  
- Next Meeting: 

## Meeting Soundbite

[**TO BE DONE**]: fill out after the meeting. Please see [Breakout Room Summaries below](#breakout-room-summaries)

## Breakout Rooms

0. Welcome
1. Japanese
2. Indonesian
3. English / Eastern Africa
4. Vietnamese
5. Catalyst School

## Run sheet

1. Welcome
2. Proposer CA assement reviews.
3. Remind people of Ideafest
4. Catalyst School - **“How to become vCA”** 
5. Breakout Rooms

## Attendee Numbers

EHT # | Date | Participants | Japan | Indonesia | Vietnam | English | Korean | Catalyst School
23 | 26.03.2022 | 60 | 16 | 18 | 17 | 9 | -- | --

## Meeting Soundbite

[**TO BE DONE**]: fill out after the meeting. Please see [Breakout Room Summaries below](#breakout-room-summaries)

## Hosts

Hosts, please arrive 30mins before the start of the Townhall to make last-minute adjustments to the schedule and go over the run sheet.

- Yuta Yuta (@cardanoz)
- Mie Tran (@Mietran0407)
- Linh (@Linh-LP)
- Tien Nguyen Anh (@tienna)
- Andreas Sosilo (@andreassosilo) 
- Andre Chyadi
- Ayu Kusummaningtyas
- Andy Sibuea (@zicozibu)
- Yan Tirta (@YanTirta)
- Angela Gatende (@A-W-G)

### Appologies
- Robert O'Brien (@wolstaeb)

### Indonesian
![photo6192756483763056381](https://user-images.githubusercontent.com/82072426/160330364-4994ef19-94f9-4037-a775-9399b593d46a.jpg)

For Indonesia break out room, we will covers these topics:
- AMA (Ask Me Anything)
- Recap / Retrospective from being CA in Fund 8
- How to register voting using wallet in Fund 8
- How to be vCA in Fund 8
[See the forum post](https://forum.cardano.org/t/eastern-town-hall-indonesia-meetup-how-to-become-vca-in-fund-8-26-mar-2022/98352).

### Japan

[**TO BE DONE**]: fill out after the meeting. 
### Vietnam

[**TO BE DONE**]: fill out after the meeting. 
### Korea

[**TO BE DONE**]: fill out after the meeting. 
### English

[**TO BE DONE**]: fill out after the meeting. 

## Catalyst School

These are the proposed Catalyst School workshop schedule:

- Saturday, 26 Feb 2022 -> Topic: “Proposing in Catalyst”
- Saturday, 12 Mar 2022  -> Topic:  “How to become CA” 
- Saturday, 26 Mar 2022 -> Topic:  “How to become vCA” 

## Fund 8 Challenges

- [Developer Ecosystem](https://easterntownhall.com/catalyst/fund8/challenges/developer-ecosystem/campaign-brief/)
- [Open Source Development Ecosystem](https://easterntownhall.com/catalyst/fund8/challenges/open-source-development-ecosystem/campaign-brief/)
- [Nation Building Dapps](https://easterntownhall.com/catalyst/fund8/challenges/nation-buidling-daaps/campaign-brief/)
- [Cross-Chain Collaboration](https://easterntownhall.com/catalyst/fund8/challenges/cross-chain-collaboration/campaign-brief/)
- [Cardano scaling solutions](https://easterntownhall.com/catalyst/fund8/challenges/cardano-scaling-solutions-/campaign-brief/)
- [DApps and Integrations](https://easterntownhall.com/catalyst/fund8/challenges/dapps-and-integrations/campaign-brief/)
- [Scale-UP Cardano's Community Hubs](https://easterntownhall.com/catalyst/fund8/challenges/scale-up-cardanos-community-hubs/campaign-brief/)
- [Gamers On - Chained](https://easterntownhall.com/catalyst/fund8/challenges/gamers-on-chained/campaign-brief/)
- [Miscellaneous Challenge](https://easterntownhall.com/catalyst/fund8/challenges/miscellaneous-challenge/campaign-brief/)
- [Grow Africa, Grow Cardano](https://easterntownhall.com/catalyst/fund8/challenges/grow-africa-grow-cardano/campaign-brief/)
- [Accelerate Decentralized Identity](https://easterntownhall.com/catalyst/fund8/challenges/accelerate-decentralized-idenity/campaign-brief/)
- [Grow East Asia, Grow Cardano](https://easterntownhall.com/catalyst/fund8/challenges/grow-east-asia-grow-cardano/campaign-brief/)
- [Business Solutions (B2B & B2C)](https://easterntownhall.com/catalyst/fund8/challenges/business-solutions-b2b-b2c/campaign-brief/)
- [Lobbying for favorable legislation](https://easterntownhall.com/catalyst/fund8/challenges/lobbying-for-favorable-legislation/campaign-brief/)
- [Improve and Grow Auditability](https://easterntownhall.com/catalyst/fund8/challenges/improve-and-grow-auditbility/campaign-brief/)
- [The Great Migration (from Ethereum)](https://easterntownhall.com/catalyst/fund8/challenges/the-great-migration-from-ethereum/campaign-brief/)
- [Open Standards & Interoperability](https://easterntownhall.com/catalyst/fund8/challenges/open-standards-and-interoperability/campaign-brief/)
- [New Member Onboarding](https://easterntownhall.com/catalyst/fund8/challenges/new-member-onboarding/campaign-brief/)
- [Self-Sovereign Identity](https://easterntownhall.com/catalyst/fund8/challenges/self-sovereign-identity/campaign-brief/)
- [Film + Media (FAM) creatives unite!](https://easterntownhall.com/catalyst/fund8/challenges/film-and-media-creatives-unite/campaign-brief/)
- [Community Advisor Improvements](https://easterntownhall.com/catalyst/fund8/challenges/community-advisor-improvements/campaign-brief/)
- [Grow India, Grow Cardano](https://easterntownhall.com/catalyst/fund8/challenges/grow-india-grow-cardano/campaign-brief/)

## Eastern Town Hall Social Media Links
 
- Meetup: [Eastern Townhall Events](https://bit.ly/3H9Xvoo)
- [Zoom](https://zoom.us/meeting/register/tJIrcumprTssEtN_RkkiNfKkyWmKn2G65mX3)
- Telegram: https://bit.ly/3H6nEo2
- Discord: https://bit.ly/3r0PP21
- Twitter: https://bit.ly/3u4EOhZ
- Email: [eastern.townhall@gmail.com](mailto:eastern.townhall@gmail.com)

**Comment by Mietran0407** [comment]
On the 26th of March, there are a total of 17 members in the Vietnamese breakout room. We decided to have 2 sessions for Ideafest Reels (one on Mar 26th and one on Apr 9th) as we are afraid there will be not enough slots for 44 proposals. There were 2 proposals turned up at the first session and we also spent the rest of the meeting discussing the proposal's flagging process, CA works, and vCA work.
