### ISSUE TITLE
Event [Townhall]: Organise Ideafest Reel - 9th April 2022 0900 to 11:00 UTC

### ISSUE THREAD

**Issue by wolstaeb** [C3ETH/c3eth-operations#139]
**TBD**: Organise Mini Ideafest for the upcomming eastern townhall.

## Scope

Not only for the sake of our proposals but also having IdeaFest Reels is a part of our KPI. The following is my suggestion in order for our IdeaFest Reels to have a greater impact :

1. Blast the event through all social channels (e.g. Twitter, Discord, Telegram and etc.), this also includes our local community partners from Cardano Foundation (e.g. Cardano Japan, Cardano Viet Nam, Cardano Indonesia and etc.)

2. In conjunction with blasting the event, we should also blast the registration form. I have made a preliminary registration form for IdeaFest Reels.

3. We should also start preparing visuals and schedules when to blast the event. (e.g. posters, Twitter banners, blast every day, blast every second day and etc.)

A preliminary [registration form for IdeaFest Reels](https://docs.google.com/forms/d/e/1FAIpQLSdVM_pYxglNbioEwNm299xhZzlDkeIx-wVokIcv1h-KjsY5gQ/viewform). Please have a look, please share your input and please feel free to share your critique. The quicker the better, for than I will be able to update. Personally I would like to blast the following finalized registration form to our respective and larger community by Monday.

**Comment by wolstaeb** [comment]
Comments from @YanTirta [in discord](https://discord.com/channels/868850218995707914/875343499824889947/960836940779884624):

In IdeaFest Reels the following people from the team will be presenting the C3ETH, Catalyst School, and Grow East Asia Challenges.
 
1. Grow East Asia, Grow Cardano - @Linh-LP 
2. Eastern Town Hall Team Operation - @YanTirta 
3. Connecting Asian Voter and Proposer - @Mietran0407 
4. Onboarding East Asia Today - @tienna 
5. Eastern Catalyst School - Syarbel

**Comment by Linh-LP** [comment]
For Main Session:
By 5:00 UTC 9 April 2022
- [ ] Core Team confirm the number of presentation from https://docs.google.com/spreadsheets/d/1W4mVCC-p6-tmlYukXYh4Xm90zqQ99S7bI83AD-NvlOw/edit#gid=416105941
- [ ] Is all proposal contain a direct link to https://cardanocataly.st/ca-tool/#/ yet?
- [ ] JP Check? @cardanoz 
- [ ] ID check? @YanTirta 
- [ ] VN check? @Linh-LP 
- [ ] EN check @A-W-G 

Vietnam breakout room
- [ ] Mei/Tien/Linh confirm who will present in VNese breakout room @Mietran0407 @tienna @Linh-LP 
- [ ] VN present registered https://docs.google.com/spreadsheets/d/1ofISYffd8XN7a80TpmRuDt4xbAIYGHW46ohy_vJqnf8/edit#gid=0
- [ ] PPT in column E or direct link for each https://cardanocataly.st/ca-tool/#/ - Check?

@wolstaeb  please start at least 30 mins to run over the session
@A-W-G will do English recording if possible, if not please advise. Please where to upload the IdeaFest after recording 
@Linh-LP will run Main English sharing screen with https://cardanocataly.st/ca-tool/#/  and https://docs.google.com/spreadsheets/d/1W4mVCC-p6-tmlYukXYh4Xm90zqQ99S7bI83AD-NvlOw/edit#gid=416105941 @YanTirta please add Yuta/Linh/Angela/Robert etc. for editing this file before 5:00 UTC (Should not do it now, some one may accident move data)
@Mietran0407 @YanTirta @cardanoz @wolstaeb @andreassosilo @andrecahyadi @zicozibu @tienna @A-W-G please comment/advise/amend any thing here so we can have smooth IdeaFest.

**Comment by andreassosilo** [comment]
@Linh-LP : it would be great if we have the name of the proposers and also the country where they are from in the Google Docs document, instead of only their e-mail address and the link to IdeaScale. Because we want to mix them, like what we did in the last IdeaFest Reels last time.

**Comment by YanTirta** [comment]
Regarding this following file : https://docs.google.com/spreadsheets/d/1W4mVCC-p6-tmlYukXYh4Xm90zqQ99S7bI83AD-NvlOw/edit#gid=416105941 this file is automatically generated from the registration form at this link : https://forms.gle/YS62WjN2QQK1QZY47

With that said, I would suggest rather than edits to please urge your community register to that form _(except for the Vietnamese community that have already registered through your form @Linh-LP for to my understanding they will be automatically added by @wolstaeb)_ . Hence I mentioned in our publication that 16 out of the 27 slots are already taken.

I aim for tomorrow 17.00 UTC to be Registration Cut-off, and 21.00 UTC to be Participants Participation Confirmation email to sent out. Whaddya think @C3ETH/c3eth-team ?

**Comment by YanTirta** [comment]
> @Linh-LP : it would be great if we have the name of the proposers and also the country where they are from in the Google Docs document, instead of only their e-mail address and the link to IdeaScale. Because we want to mix them, like what we did in the last IdeaFest Reels last time.

Great idea @andreassosilo . This could be great input for our future IdeaFest Reels, but for now I believe the emails majority represent the participants name too. Regarding mixing based on country I would rather suggest to be based on their type of presentation as mentioned in the registration form. Whaddya think @C3ETH/c3eth-team ?

**Comment by Linh-LP** [comment]
_Personal view:_ Let it be country-less as _blockchain architecture_, _Cardano and Project Catalyst._ We (Core Team) can mention the communities we tent to support and attendees, let them intro if they wish to, otherwise no need the origin of proposers but focus on quality and the impact of the proposal.

**Comment by Linh-LP** [comment]
> > @Linh-LP : it would be great if we have the name of the proposers and also the country where they are from in the Google Docs document, instead of only their e-mail address and the link to IdeaScale. Because we want to mix them, like what we did in the last IdeaFest Reels last time.
> 
> Great idea @andreassosilo . This could be great input for our future IdeaFest Reels, but for now I believe the emails majority represent the participants name too. Regarding mixing based on country I would rather suggest to be based on their type of presentation as mentioned in the registration form. Whaddya think @C3ETH/c3eth-team ?

Personal view: Let it be country-less as blockchain architecture, Cardano and Project Catalyst. We (Core Team) can mention the communities we tent to support and attendees, let them intro if they wish to, otherwise no need the origin of proposers but focus on quality and the impact of the proposal.

**Comment by andrecahyadi** [comment]
Yeah, I agree with Linh. Let the proposers speak about what they want to promote their proposals.

We will tell the audience the proposals presented here are from the Eastern town hall community members ranging from Japan, Vietnam, Indonesia, New Zealand, and East Africa. We hope to see more friends from other Eastern Hemisphere countries join this movement. 
Add a short explanation about Global Townhall, LATAM, Pacific, and others to show the vast Cardano community networks.  These proposals, hopefully, can further develop Cardano and have positive impacts on the community.

**Comment by wolstaeb** [comment]
Comments from @cardanoz in discord.

From Japan,there are 4 project joining fest🙇‍♂️

CARDANO SAY NO PLASTIC STRAWS | CADANO FOR OCEAN
Blockchain and Cardano Library
Exhibit Largest BlockChainEXPO(JP)
Challenge & Scouted for Students🎓

**Comment by Mietran0407** [comment]
Hi everyone, I checked for the Japanese link and there are 11 proposals in total, some are newly registered.

There are some proposals in Vietnam that want to present in Japanese in the Japanese room, will we have a separated Japanese breakout room or all of the proposal will be in the main room and use English, thank you for everyone's clarification.

**Comment by YanTirta** [comment]
> 

@Mietran0407 , to my understanding from @cardanoz excel file header, which says "Catalyst-IdeaFEST FUND8 _Japanese Room_ Form", it suggest that those are participants in the Japanese Breakout Room. If that is the case, then it is most likely it will be in Japanese.

Please correct me if I am wrong.

**Comment by wolstaeb** [comment]
[Ideafest Recording on Youtube](https://youtu.be/t86e0M-262A). We still need to update all the timecodes for the proposers.
