### ISSUE TITLE
Catalyst TV Videos

### ISSUE THREAD

**Issue by Mietran0407** [C3ETH/c3eth-operations#142]
## Objectives

Posting videos of Catalyst TV on the Eastern Townhall landing page, coordinate with core team members to make videos for the team's proposals 

## Requirements

1. For the available videos, I will send Jack the original videos plus the Youtube links, please let me know if you need any things else.
2. For the ETH's proposals, please let me know if you are comfortable doing a 5 minutes interview for 5 proposals, please comment down below the proposal you want to do and I will be in touch soon, it will take only 15 - 20 minutes.
 
You can find all our Eastern Town Hall proposals at these links :

- [x] [Eastern Town Hall Team Operation](https://cardano.ideascale.com/c/idea/403802) - @wolstaeb 
- [x] [Connecting Asian Voter and Proposer](https://cardano.ideascale.com/c/idea/404182) - @tienna 
- [ ] [Onboarding East Asia Today](https://cardano.ideascale.com/c/idea/404177)
- [ ] [Grow East Asia, Grow Cardano](https://cardano.ideascale.com/c/idea/399482)
- [ ] [Eastern Catalyst School](https://cardano.ideascale.com/c/idea/405311)

## Youtube Videos 

[Video published on Youtube ](https://www.youtube.com/playlist?list=PLgIO96BXrRnb51UTv6rvDcOH6YebH8RAN)

- [ ] [Eastern Town Hall Team Operation]() 
- [ ] [Connecting Asian Voter and Proposer]() 
- [ ] [Onboarding East Asia Today]()
- [ ] [Grow East Asia, Grow Cardano]()
- [ ] [Eastern Catalyst School]()

As the videos are posted please create a new issue in the [c3eth.github.io repository](https://github.com/C3ETH/c3eth.github.io/issues/new/choose) using the [template for that purpose](https://github.com/C3ETH/c3eth.github.io/issues/new?assignees=&labels=documentation%2Chelp+wanted&template=add-update-page.yml&title=%3Apage_facing_up%3A+Add+new+page%2Fdocument+for+%3CTITLE%3E).

**Comment by Mietran0407** [comment]
Please kindly help me choose the proposal you want to be interviewed for if you are comfortable doing it @zicozibu @A-W-G @cardanoz @Linh-LP @wolstaeb @andreassosilo @YanTirta, there are 4 lefts

You can find all our Eastern Town Hall proposals at these links :

1. Eastern Town Hall Team Operation - https://cardano.ideascale.com/c/idea/403802
2. Connecting Asian Voter and Proposer - https://cardano.ideascale.com/c/idea/404182 - @tienna 
3. Onboarding East Asia Today - https://cardano.ideascale.com/c/idea/404177
4. Grow East Asia, Grow Cardano - https://cardano.ideascale.com/c/idea/399482
5. Eastern Catalyst School - https://cardano.ideascale.com/c/idea/405311

**Comment by wolstaeb** [comment]
I will do the Eastern Town Hall Team Operation proposal. We do the call at 4AM UTC? That should be 10AM for you. If not, then 7AM UTC will work for me.

Also if you up for a little challenge. @Mietran0407 would you be interested in learning to use [DScript](https://www.descript.com/) with me and Jack?
