### ISSUE TITLE
Event [Townhall]: Eastern Hemisphere Townhall Event #25 - 23rd April 2022 0900 to 11:00 UTC

### ISSUE THREAD

**Issue by wolstaeb** [C3ETH/c3eth-operations#149]
Register for [Eastern Townhall Events](https://bit.ly/3H9Xvoo) via the Cardano and Catalyst Community Network on meetup.com. 

- [Meeting Link](https://zoom.us/meeting/register/tJIrcumprTssEtN_RkkiNfKkyWmKn2G65mX3)
- [Openning Presentation](https://docs.google.com/presentation/d/1S3xmZlQG5GsMcLRyaKno9FuOQ59GrQZs/edit#slide=id.p1)
- [Eastern Townhall Community Calendar](https://calendar.google.com/calendar/embed?src=kg3go90c7fu4jr1fsqk00h43b4%40group.calendar.google.com&ctz=Etc%2FGMT)
- Last Meeting: #144 
- Next Meeting: 

## Meeting Soundbite

[**TO BE DONE**]: fill out after the meeting. Please see [Breakout Room Summaries below](#breakout-room-summaries)

## Breakout Rooms

0. Welcome
1. Japanese
2. Indonesian
3. Vietnamese
4. Pilipinas

## Run sheet

1. Welcome and Welcome to Philippines
2. [CCv3 Catalyst Circle - Code of Conduct](https://pol.is/5xuvbiv25u)
3. [Eastern Townhall Proposals](https://cardanocataly.st/voter-tool/#/f8/shared/c4d2f616-0cd5-452d-9f90-7122c8a2b940).
4. Breakout Rooms

## Attendee Numbers

EHT | Date | Participants | Japan | Indonesia | Vietnam | English | Pilipinas | Catalyst School
-- | -- | -- | -- | -- | -- | -- | -- | --
25 | 23.04.2022 | 36 | 12 | 5 | 17 | 1 | 1 | --

## Meeting Soundbite

[**TO BE DONE**]: fill out after the meeting. Please see [Breakout Room Summaries below](#breakout-room-summaries)
## Hosts

Hosts, please arrive 30mins before the start of the Townhall to make last-minute adjustments to the schedule and go over the run sheet.

- Yuta Yuta (@cardanoz)
- Mie Tran (@Mietran0407)
- Linh (@Linh-LP)
- Andreas Sosilo (@andreassosilo) 
- Yan Tirta (@YanTirta)
- Robert O'Brien (@wolstaeb)
- Julius Mark Ibanez

### Indonesian

[**TO BE DONE**]: fill out after the meeting. 

### Japan

[**TO BE DONE**]: fill out after the meeting. 

### Vietnam

Topic: CA result sharing and Proposals' sharing method
Duration: 2,5 hours

Today we had 17 participants in the Vietnamese break-out room. We asked the community one by one to share their experience with the CA round as well as share their experiences collected and their Marketing strategy for their proposals.

### Philippines

Mark Ibanez attended the Eastern Townhall as a host. In the future we will be promoting Catalyst to the community in the Philippines.

## Eastern Town Hall Social Media Links
 
- Meetup: [Eastern Townhall Events](https://bit.ly/3H9Xvoo)
- Zoom: [Eastern Townhall Zoom](https://zoom.us/meeting/register/tJIrcumprTssEtN_RkkiNfKkyWmKn2G65mX3)
- Telegram: https://bit.ly/3H6nEo2
- Discord: https://discord.gg/pnq3CZuUjC
- Twitter: https://bit.ly/3u4EOhZ
- Email: [eastern.townhall@gmail.com](mailto:eastern.townhall@gmail.com)

**Comment by Linh-LP** [comment]
Possible to populate the CCv3 Catalyst Circle - Code of Conduct - Wiki Survey
https://pol.is/5xuvbiv25u

**Comment by Mietran0407** [comment]
Eastern Town Hall Viet Nam

Topic: CA result sharing and Proposals' sharing method
Duration: 2,5 hours

Today we had 17 participants in the Vietnamese break-out room. We asked the community one by one to share their experience with the CA round as well as share their experiences collected and their Marketing strategy for their proposals.

**Comment by wolstaeb** [comment]
@YanTirta and @cardanoz can you add a little update on activities in your room please.

**Comment by YanTirta** [comment]
Sure thing @wolstaeb !

**Eastern Town Hall Indonesia**

**Topic :** Test a new concept called Career Day AMA _(Ask Me Anything)_
**Duration :** 1 hour 5 minutes

For this session we had only 4 participants. We informed the community that Eastern Town Hall will be creating a series of task-based bounties. And as agreed on our Monday meeting, one bounty that would be given to the community is for a **JavaScript/CSS Developer** to gradually take on the duties of @PardusEidolon . Besides that, we also informed the community that Genius Yield is looking for an Indonesian Ambassador.

You can find the our following presentation here : [Career Day AMA Presentation](https://drive.google.com/file/d/1CDVuCWWD464V4i_X39Npxdyu7DiwRc44/view?usp=sharing)
