### ISSUE TITLE
Meeting [Townhall]: Prepare Indonesia Breakout Room for 23 April 2022

### ISSUE THREAD

**Issue by wolstaeb** [C3ETH/c3eth-operations#154]
Organise any activity associated with organising and preparing a breakout room session.

- [x] Discussion with team to collect ideas for the upcomming session.
- [x] Arrange and attend a [team meeting]().
- [x] Organise and communitcate with guest speakers.
- [x] Prepare a [presentation]() for the breakout room (create a separate issue for this please)
- [x] Inform the community about the upcomming event across social media channels.

**Comment by andreassosilo** [comment]
Done

**Comment by YanTirta** [comment]
Pardon @wolstaeb , can you please teach me how to send our weekly meeting invite/agenda out to the team?
