### ISSUE TITLE
Catalyst[Voting]: Voting with the C3ETH Wallet for Fund 8

### ISSUE THREAD

**Issue by Mietran0407** [C3ETH/c3eth-operations#156]
## Objectives

Use the C3ETH Wallet to vote for Eastern Hemisphere proposals and use the compiled list to cross-marketing

## Eastern Hemisphere proposals

Below is the compiled list and it would be great if we can divide them up and help vote whenever you have time by our C3ETH wallet (password will be sent via 1password) as it is estimated more than 100 proposals

- [x] Eastern Townhall and Indonesia proposal: https://cardanocataly.st/voter-tool/#/f8/shared/68281643-03dd-433d-aaba-f5b637ef8ead
- [x] Vietnamese proposals: 
https://cardanocataly.st/voter-tool/#/f8/shared/6ab3a00c-a273-498b-a295-4023240b0907
- [x] East Africa proposals: https://cardanocataly.st/voter-tool/#/f8/shared/6ca5321a-b343-4812-ae92-1ebf197ec32f
- [x] Japanese proposals: pending
- [ ] Philippines proposals: pending

We will need @cardanoz and @markibanez support with the link of Japanese and Phillippine proposals. Thank you for your support. ^^

**Comment by Mietran0407** [comment]
I used the Eastern Townhall wallet to vote for Eastern Townhall, Indonesian, Vietnamese and East Africa's proposals already.

**Comment by Mietran0407** [comment]
If you already have the proposal list, please feel free to send me the link and I will help share and vote for it @cardanoz @markibanez. Thank you ^^

**Comment by wolstaeb** [comment]
Voting is now closed.
