### ISSUE TITLE
Meeting [Team Checkin]: Core Team Weekly 2nd May 2022 - 0800 to 1000 UTC

### ISSUE THREAD

**Issue by wolstaeb** [C3ETH/c3eth-operations#160]
## Review

1. Plans for the next townhall. 
2. Fund 8 Voting
3. Task-Based Compensation

**NOTE**: To help everyone to fully participate in the team meetings we will be recording the meeting using otter.ai. We'll use the transcription to also help create notes before deleting the recording.

## Meeting Details:

- Last Meeting:  #153  
- Next Meeting:  

### Team Calenders:

- [C3ETH Team Calendar](https://calendar.google.com/calendar/embed?src=2g3h5vj0cui84imibn6bpa4tr4%40group.calendar.google.com&ctz=Etc%2FGMT)
- [Eastern Townhall Community Calendar](https://calendar.google.com/calendar/embed?src=kg3go90c7fu4jr1fsqk00h43b4%40group.calendar.google.com&ctz=Etc%2FGMT)
- [Meeting Link](https://us02web.zoom.us/j/89664896982?pwd=RDlQNDRYTlZFZWVDWklvcXBqeFM0UT09)

### Attendees:

- Yuta Yuta (@cardanoz)
- Mie Tran (@Mietran0407)
- Linh (@Linh-LP)
- Tien Nguyen Anh (@tienna)
- Andreas Sosilo (@andreassosilo) 
- Andy Sibuea (@zicozibu)
- Yan Tirta (@YanTirta)
- Angela Gatende (@A-W-G)
- Julius Mark Ibanez (@markibanez)
- Paul Ko (@haskellcoding29 )

### Apologies:

- Robert O'Brien (@wolstaeb)

### Topics to cover

1. General catch-up with each other.
2. Catalyst Updates - Revised plan/schedule for Fund 9
5. Fund 8 Voting - Please complete the sub-tasks in #156 
6. Plans for the next townhall. 
7. Reminder about Task-based comphensation for March/April
8. Challenge Team "F8: Grow East Asia, Grow Cardano"

#### Revised Schedule for Fund 9.
![Fund9-Schedule-2022-05-02](https://user-images.githubusercontent.com/82072426/166193741-ff01608e-6c40-4317-8eca-396f84d5b5d8.png)

#### Task-based Compensation

@wolstaeb will work on geting this done on 5th May. Please ensure all tasks are entered and/or information is sent to @wolstaeb by then.

#### Challenge Team F8: Grow East Asia, Grow Cardano
- Challenge Team Round Table 5 on Friday, 06 May 2022
- Please confirm again with @Linh-LP (team lead), if you want to participate or not as Challenge Team
- Make a list of funded proposal on this challenge category on the Excel sheet
- Team lead will receive the contact list from IOG
- We need to create proof-of-life on each funded proposer

#### Eastern Town Hall Meetup
- There will be no Indonesia breakout room due to the holiday for this Saturday
- @markibanez : contacting Facebook group, create Discord server, hopefully they will join the Philippines  break out room this Saturday
- Vietnam breakout room: hosting normal breakout room, will prepare the topic for that
- @A-W-G : normal discussion in English break out room

#### Preparation for Fund 9 Proposal
- We need to prepare 5 proposals for Fund 9 for Eastern Town Hall projects/operations.
- Does F8: Grow East Asia, Grow Cardano help our Eastern Town Hall community? Should we continue this category in the future?

**Comment by wolstaeb** [comment]
Comments from @cardanoz in Discord. 

Review
Plans for the next townhall.
⇨I will share the Fund 7 survey as soon as I can, but the full Fund 7 survey will be shared by the AIM team after Fund 8.

Fund 8 Voting
⇨I will remind you to vote again before the meeting.

General catch-up with each other.
⇨ The Japanese community seems to be somewhat confused by the YOROI glitch. We recommend contacting support; some people claim they can no longer participate in Catalyst.

Catalyst Updates - Revised plan/schedule for Fund 9
⇨I will share again with the Japanese community at the right time before the meeting.

**Comment by andreassosilo** [comment]
Done. Issue closed.
