### ISSUE TITLE
Operations [Renumeration]: Team Payments for May.

### ISSUE THREAD

**Issue by wolstaeb** [C3ETH/c3eth-operations#191]
As per our consensus and #102, pay @C3ETH/c3eth-team remuneration for May 2022. Perform the payment in one transaction for transparency and accountability purposes.

- [x] #102 
- [x] Get the 7-Day Average USD/ADA price from [coinmarketcap.com](https://bit.ly/3fVrYKT). See details below.
- [x] [Update compensation spreadsheet](https://bit.ly/3H1G8G7) with exchange rate, and
- [x] Work out Ada/Lovelace amounts
- [x] Double Check amounts and put them into payment script
- [x] [Transfer total amount needed](https://explorer.cardano.org/en/transaction?id=f1e165ee0c04da30244db3c8bb092ab2a9b3af6498beb6884f19c58a420a906b) to the local payment address.
- [x] Update script with input transaction details
- [x] [Perform the renumeration payment](https://explorer.cardano.org/en/transaction?id=03d4655297c567aafd52152676143349c01a52cf495a032b36cabf9f96566f99)
- [x] [Notify the @C3ETH/c3eth-team of the transaction](dsicord:https://discord.com/channels/868850218995707914/875343499824889947/977478930938339398).
- [x] Backup payment script details.
- [x] Document transaction details

---
## Transaction Details

Links above document the payment plan and the two associated transactions.

### Coin marketcap 7-Day rate

For Payment we use a simple seven day average to devise the payment conversion rates at the approximate time (within 30mins of) the payments being made. The USD/ADA rate is calculated using the following data points from Coinmarket Cap 7D prices. The intention is to smooth out fluations in the USD/ADA exchange rates.

```
ADA-7DA = (7DOPEN + 7DCLOSE + HIGH + LOW) / 4
```

Where: 7DOPEN, 7DCLOSE, HIGH, LOW are USD/ADA prices. HIGH and LOW are the Coinmarket Cap 7d Low/High, and the 7DSTART and 7DCLOSE are taken from the seven day window of the chart below.

PERIOD | 7DOPEN | 7DCLOSE | 7DLOW | 7DHIGH | AVG
-- | -- | -- | -- | -- | --
May | 0.5328 | 0.5322 | 0.6073 | 0.493 | 0.541325

![Screen Shot 2022-05-21 05 59 31 PM](https://user-images.githubusercontent.com/82072426/169640328-3a9a1233-e9b1-4a88-8921-bef2dbad6537.png)

**Comment by andrecahyadi** [comment]
@wolstaeb Hi, Robert, I just saw the team compensation sheet in detail yesterday, https://docs.google.com/spreadsheets/d/1I4eG9oCaQDHoqa4MAtAYujynGP522be2mezoMdVbwoE/edit#gid=593643092. 
Some questions that I'd like to ask if you don't mind :) 
* Have you tried using AdaLite to pull wallet's transactions in detail (in 'Send' tab, select Export to CSV)? I use AdaLite to manage Cardano Indonesia's treasury. You can connect hardware wallets as well in AdaLite. 
Screenshot example (*asset displays NFTs)
<img width="863" alt="image" src="https://user-images.githubusercontent.com/95466316/169700028-7baaf5e0-c50e-4c5e-a480-91b94fd0f337.png">
* Those 12k amounts supposed to be different? How do you decide the budget ratio? And, I assume 'Task Payments' is for Task Compensation, what about culture & community payments, any detail explanation? 
<img width="744" alt="image" src="https://user-images.githubusercontent.com/95466316/169700273-61f95573-d783-409e-aa98-eed116ff76a3.png">

**Comment by wolstaeb** [comment]
@andrecahyadi 

> Have you tried using AdaLite to pull wallet's transactions in detail 

The Wallet keys are management with a hardware/wallet. And these records are just pulled from the Daedalus CSV export (similar to AdaLite).

> Those 12k amounts supposed to be different? How do you decide the budget ratio? 

Yes they are different. The bottom figures are set at the beginning of the quarter based on the proposals that have been funded. The ratios where just set arbitrarily, discussed and refined with the team. With each quarter we will set the budget and adjust ratios accordingly.

The topline $12K figure about is the actuals. Because of USD/ADA currency flutuations the budget is only an approximate guide.  

The culture payments were set small this time around because we are just working this out. The Community Payments come from the proposal's themselves.  

> I assume 'Task Payments' is for Task Compensation

Yes.

> what about culture & community payments, any detail explanation?

Communty payments are for payments to the wider community, not the core-team. These a bounty like programmes. The first of which is for doing translations of content (Catalyst Fund Challenges).

The culture payments (or _Praise_) is the for the core team to reward contributions made by individuals in the team and in the community. It is based on the assumption that we are the best people to reward each other for valuable contributions that can't, aren't, or shouldn't be forced into the task-based payments. 

Each period a certain number Praise tokens (unique to that period) will be issued to core-team members plus some ADA (to account for transaction fees and minimum ADA requirements). Core team members can then *Gift* tokens to other people in the Core Team or in the community. These tokens are only worth something if they have been gifted to someone else. At the end of a period people can redeem the _praise tokens gifted_ to them in return for ADA. Only praise tokens that have been gifted at least once can be redeemed.

**Comment by andrecahyadi** [comment]
Hi Robert @wolstaeb, I put my questions below your answers.

> @andrecahyadi
> 
> > Have you tried using AdaLite to pull wallet's transactions in detail
> 
> The Wallet keys are management with a hardware/wallet. And these records are just pulled from the Daedalus CSV export (similar to AdaLite).
>>> Got it, because on the sheet, I didn't see the time stamps like 07:05 AM UTC, 02:22 PM UTC, etc.
<br>

>  Those 12k amounts supposed to be different? How do you decide the budget ratio?
> 
> Yes they are different. The bottom figures are set at the beginning of the quarter based on the proposals that have been funded. The ratios where just set arbitrarily, discussed and refined with the team. With each quarter we will set the budget and adjust ratios accordingly.
> 
> The topline $12K figure about is the actuals. Because of USD/ADA currency flutuations the budget is only an approximate guide.
>>> Noted
<br>

> The culture payments were set small this time around because we are just working this out. The Community Payments come from the proposal's themselves.
> 
> > I assume 'Task Payments' is for Task Compensation
> 
> Yes.
> 
> > what about culture & community payments, any detail explanation?
> 
> Communty payments are for payments to the wider community, not the core-team. These a bounty like programmes. The first of which is for doing translations of content (Catalyst Fund Challenges).
> 
> The culture payments (or _Praise_) is the for the core team to reward contributions made by individuals in the team and in the community. It is based on the assumption that we are the best people to reward each other for valuable contributions that can't, aren't, or shouldn't be forced into the task-based payments.
> 
> Each period a certain number Praise tokens (unique to that period) will be issued to core-team members plus some ADA (to account for transaction fees and minimum ADA requirements). Core team members can then _Gift_ tokens to other people in the Core Team or in the community. These tokens are only worth something if they have been gifted to someone else. At the end of a period people can redeem the _praise tokens gifted_ to them in return for ADA. Only praise tokens that have been gifted at least once can be redeemed.
>>> Noted for Community Payments.
>>> About Culture Payments, how would you value the tokens in ADA for redemption process? How the redemption process would be then?

**Comment by wolstaeb** [comment]
@andrecahyadi 

> About Culture Payments, how would you value the tokens in ADA for redemption process? How the redemption process would be then?

There a two primary ways. The longer-term aim is to have the redemption process tied to a Bonding Curve (think Automated Market Marker). 

Before that happens however we need to do small scale experiments to get everyone comfortable with the concepts of Priase and redeemption. So the first experiment, redepemtion will involve a manual reconciliation of transactions. The value of each praise token will be determined by the number of praise tokens gifted then redeemed in any given period. A ADA budget is set for a period, and the ADA is pro-rata according to the number of gifted tokens redeemed. Very similar to how the Task Compensation is being done.

**Comment by wolstaeb** [comment]
@andrecahyadi I'm moving the [discussion to this thread](https://github.com/C3ETH/c3eth-operations/discussions/79)

**Comment by andrecahyadi** [comment]
> @andrecahyadi
> 
> > About Culture Payments, how would you value the tokens in ADA for redemption process? How the redemption process would be then?
> 
> There a two primary ways. The longer-term aim is to have the redemption process tied to a Bonding Curve (think Automated Market Marker).
> 
> Before that happens however we need to do small scale experiments to get everyone comfortable with the concepts of Priase and redeemption. So the first experiment, redepemtion will involve a manual reconciliation of transactions. The value of each praise token will be determined by the number of praise tokens gifted then redeemed in any given period. A ADA budget is set for a period, and the ADA is pro-rata according to the number of gifted tokens redeemed. Very similar to how the Task Compensation is being done.

@wolstaeb Great explanation, Robert, really appreciate it! Thank You.
