### ISSUE TITLE
Event [Townhall]: Eastern Hemisphere Townhall Event #27 - 21 MAY 2022 0900 to 11:00 UTC

### ISSUE THREAD

**Issue by wolstaeb** [C3ETH/c3eth-operations#192]
## Meeting Details:

- Last Meeting: #172
- Next Meeting: 

- Register for [Eastern Townhall Events](https://bit.ly/3H9Xvoo) via the Cardano and Catalyst Community Network on meetup.com. 
- [Openning Presentation](https://docs.google.com/presentation/d/14Yuchu_Cuj8jbtDfEJr9HdCKeyffXrOP/edit#slide=id.g110ef5aae32_1_1281) and [Vietnam version](https://docs.google.com/presentation/d/14lhSH7nVF7_GbN_lgw0I6UBmPsKBpqID/edit?usp=sharing&ouid=101771009461790797959&rtpof=true&sd=true)
- [Overview presentation of Fund 9 challenges](https://docs.google.com/presentation/d/1UfVrbCxBlCxm7qoXJbBn2JL13B78zw759X4GZCNi_TA/edit?usp=sharing)
- [Meeting Link](https://us02web.zoom.us/j/83779080423?pwd=WFNHTlQ4Y2lPa0N0aytxVDdJbG9DUT09)
## Meeting Soundbite:

[**TO BE DONE**]: fill out after the meeting. Please see [Breakout Room Summaries below](#breakout-room-summaries)

## Breakout Rooms:

0. Welcome
1. Japanese
2. Indonesian
3. English / Eastern Africa
5. Vietnamese
6. Pilipinas

## Run sheet:

1. Welcome
2. FT X Cardano Blockchain Challenge
3. Breakout Rooms
 
## Attendee Numbers:

EHT # | Date | Participants | Japan | Indonesia | Vietnam | English | Korean | Pilipinas | Catalyst School
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
#27 | 21.05.2022 | 61| 16 | 12 | 16 | 8 | -- | -- | --

## Meeting Soundbite:

[**TO BE DONE**]: fill out after the meeting. Please see [Breakout Room Summaries below](#breakout-room-summaries)

## Hosts: 

Hosts, please arrive 30mins before the start of the Townhall to make last-minute adjustments to the schedule and go over the run sheet.

- Yuta Yuta (@cardanoz)
- Mie Tran (@Mietran0407)
- Linh (@Linh-LP)
- Tien Nguyen Anh (@tienna)
- Andreas Sosilo (@andreassosilo) 
- Ayu Kusummaningtyas
- Andy Sibuea (@zicozibu)
- Yan Tirta (@YanTirta)
- Angela Gatende (@A-W-G)
- Robert O'Brien (@wolstaeb)
- Paul Ko (@haskellcoding29)

### Indonesian

12 participants in Indonesian break out room. We are doing 1st Eastern Catalyst School workshop: "Introduction to Catalyst" in Indonesian language. [Recap for the 1st workshop: "F9: Introduction to Catalyst" in 🇮🇩 Indonesian language](https://forum.cardano.org/t/eastern-catalyst-school-indonesia-workshop-1-introduction-to-catalyst-recap/101649)

### Japan

[**TO BE DONE**]: fill out after the meeting. 

### Vietnam

On Saturday's meeting, the Vietnam breakout room had 16 attendees. We invited 4 guest speakers who are funded proposers in fund8 who got the CA score from 4.8 to share about their experiences to the community.

### English

For most of the session, Robert ran through the [Fund 9 challenges](https://docs.google.com/presentation/d/1UfVrbCxBlCxm7qoXJbBn2JL13B78zw759X4GZCNi_TA/edit#slide=id.g1173ea6a2f9_0_285) providing context, background and the objectives of each of the challenges. Yoram gave an update to Cardano4Climate and we got into a discussion around the difficulty of impact measurement.

## Related Material

Yoram has shared his intent to present in our main room. He will be bringing his contacts from Seedstars. An incubator that has official ties with Project Catalyst. You can learn more about Seedstars at [this following link](https://www.seedstars.com/community/entrepreneurs/programs/ft-cardano-blockchain-challenge/) and their [media kit](https://docs.google.com/presentation/d/1fYVL6hq4vCPXJaJyfUcdA86VaDN9QO6I/edit#slide=id.p1).

## Eastern Town Hall Social Media Links
 
- Zoom: https://us02web.zoom.us/j/83779080423?pwd=WFNHTlQ4Y2lPa0N0aytxVDdJbG9DUT09
- Web: https://easterntownhall.com/
- Telegram: https://bit.ly/3H6nEo2
- Discord: https://discord.gg/pnq3CZuUjC
- Twitter: https://bit.ly/3u4EOhZ
- Meetup: https://bit.ly/3H9Xvoo
- Email: [eastern.townhall@gmail.com](mailto:eastern.townhall@gmail.com)

**Comment by andreassosilo** [comment]
12 participants in Indonesian break out room. We are doing 1st Eastern Catalyst School workshop: "Introduction to Catalyst" in Indonesian language.

I will create the summary in Cardano Forum ASAP for today workshop.

[Recap for the 1st workshop: "F9: Introduction to Catalyst"](https://forum.cardano.org/t/eastern-catalyst-school-indonesia-workshop-1-introduction-to-catalyst-recap/101649)

**Comment by Mietran0407** [comment]
On Saturday's meeting, the Vietnam breakout room had 16 attendees. We invited 4 guest speakers who are funded proposers in fund8 who got the CA score from 4.8 to share about their experiences to the community.
