### ISSUE TITLE
Event [Townhall]: Eastern Hemisphere Townhall Event #28 - 04 JUNE 2022 0900 to 11:00 UTC

### ISSUE THREAD

**Issue by wolstaeb** [C3ETH/c3eth-operations#213]
## Meeting Details:

- Last Meeting: #192 
- Next Meeting: 

- Register for [Eastern Townhall Events](https://bit.ly/3H9Xvoo) via the Cardano and Catalyst Community Network on meetup.com. 
- [Openning Presentation](https://docs.google.com/presentation/d/1iK7bbPM0EGJE_FWTjN2rtnHx1JO8-bcp/edit#slide=id.p1)
- [Meeting Link](https://us02web.zoom.us/j/83779080423?pwd=WFNHTlQ4Y2lPa0N0aytxVDdJbG9DUT09)
## Meeting Soundbite:

[**TO BE DONE**]: fill out after the meeting. Please see [Breakout Room Summaries below](#breakout-room-summaries)

## Breakout Rooms:

0. Welcome
1. Japanese
2. Indonesian
3. English / Eastern Africa
4. Korean
5. Vietnamese

## Run sheet:

1. Welcome
2. Lido
3. Breakout Rooms - Insight Sharing

## Attendee Numbers:

EHT # | Date | Participants | Japan | Indonesia | Vietnam | English | Korean | Catalyst School
-- | --  | -- | -- | -- | -- | -- | -- | --
28  | 04.06.2022 | 59 | 18 | 17 | 16 | 8 | -- | --

## Meeting Soundbite:

[**TO BE DONE**]: fill out after the meeting. Please see [Breakout Room Summaries below](#breakout-room-summaries)
## Hosts: 

Hosts, please arrive 30mins before the start of the Townhall to make last-minute adjustments to the schedule and go over the run sheet.

- Yuta Yuta (@cardanoz)
- Mie Tran (@Mietran0407)
- Linh (@Linh-LP)
- Tien Nguyen Anh (@tienna)
- Andreas Sosilo (@andreassosilo) 
- Ayu Kusummaningtyas
- Andy Sibuea (@zicozibu)
- Yan Tirta (@YanTirta)
- Angela Gatende (@A-W-G)
- Robert O'Brien (@wolstaeb)

### Indonesian

In Indonesia break out room, we gave Eastern Catalyst Workshop: **"How to submit proposal in Catalyst Fund 9 - Part 1"** for 2 hours. Total participants: 17 people. 

**Topics to be covered:**

- What is Project Catalyst
- Short intro to Catalyst Fund 9
- Explanation for several category challenge
- IdeaScale
- How to submit proposal in IdeaScale
- Q&A

@andreassosilo will create recap of our Eastern Catalyst School workshop in Cardano Forum soon. See [recap in Cardano Forum](https://forum.cardano.org/t/eastern-catalyst-school-indonesia-workshop-2-how-to-submit-proposal-in-catalyst-part-1-recap/102626)

### Japan

[**TO BE DONE**]: fill out after the meeting. 

### Vietnam

[**TO BE DONE**]: fill out after the meeting. 

### English

[**TO BE DONE**]: fill out after the meeting. 
## Eastern Town Hall Social Media Links
 
- Zoom: https://us02web.zoom.us/j/83779080423?pwd=WFNHTlQ4Y2lPa0N0aytxVDdJbG9DUT09
- Web: https://easterntownhall.com/
- Telegram: https://bit.ly/3H6nEo2
- Discord: https://discord.gg/pnq3CZuUjC
- Twitter: https://bit.ly/3u4EOhZ
- Meetup: https://bit.ly/3H9Xvoo
- Email: [eastern.townhall@gmail.com](mailto:eastern.townhall@gmail.com)

**Comment by andreassosilo** [comment]
In Indonesia break out room, we gave Eastern Catalyst Workshop: "How to submit proposal in Catalyst Fund 9 - Part 1" for 2 hours. Total participants: 17 people (I think max hit 18 people).

I will create the recap in Cardano Forum soon.

**Comment by andreassosilo** [comment]
See Indonesia break out room [recap in Cardano Forum](https://forum.cardano.org/t/eastern-catalyst-school-indonesia-workshop-2-how-to-submit-proposal-in-catalyst-part-1-recap/102626)
