### ISSUE TITLE
Meeting[Eastern Catalyst School]: 1:1 meeting with proposer in Fund 9

### ISSUE THREAD

**Issue by tienna** [C3ETH/c3eth-operations#219]
*Objectives:**
- Make sure the proposer understands about Catalyst F9 timeline
- Support the proposer to overcome his barriers in writing the proposal

 *Tasks:**

- [x] Explain with Proposer about Catalyst Fund9 timeline from 20:00 to 21:00 8th June 2022
- [x] Address questions from Proposer in writing his proposal
- [x] Schedule for the next meeting

**Comment by tienna** [comment]
Tasks completed

**Comment by andreassosilo** [comment]
@tienna : Please add VN in the end of the title [1-on-1 meeting with proposer in Fund 9 (VN)], so this indicate 1-on-1 meeting support for Vietnamese proposer/community. Thanks mate.
