### ISSUE TITLE
Operations [Treasury]: Payment for Eastern Catalyst School Indonesia July 2022

### ISSUE THREAD

**Issue by syarbel** [C3ETH/c3eth-operations#306]
Perform the payment to project teams handling the operations of the Eastern Catalyst School - Indonesia (remuneration for JULY) 2022  in one transaction for transparency and accountability purposes.

- [x] Workout the ADA amount received from transaction details
- [x] [Workout Compensation detail and Payment summary sheet](https://docs.google.com/spreadsheets/d/1tW3nnDIjvPkynjEJtVSXHNdKB3t3BISN6QOSfFXqsw4/edit?usp=sharing) @syarbel 
- [x] Double Check amounts and put them into payment script
- [x] [Perform the Indonesian Eastern Catalyst School Team payment](https://cardanoscan.io/transaction/28ac9c47094985b2cdb3365725584dac1ba93277b92b9405b1067ffcc2c00585) to the PIC's payment address. @danivideda 
- [x] Update script with input transaction details
- [x] Notify the Indonesian ECS team of the transaction.
- [x] Backup payment script details.
- [x] Document transaction details

---
## Transaction Details

Payments are made based on the ADA received from Eastern Town Hall using Ray Wallet for multiple transaction in only one outgoing transaction.

All detail compensation an transaction can see from the Gdocs: Spreadsheet above on ECS ID - Distribution.

**Comment by andreassosilo** [comment]
Done. Closed.
