### ISSUE TITLE
Event [Townhall]: Eastern Hemisphere Townhall Event #33 - 13 Aug 2022 0900 to 11:00 UTC

### ISSUE THREAD

**Issue by wolstaeb** [C3ETH/c3eth-operations#348]
## Meeting Details:

- Last Meeting: #322  
- Next Meeting: 

- Register for [Eastern Townhall Events](https://bit.ly/3H9Xvoo) via the Cardano and Catalyst Community Network on meetup.com. 
- [Openning Presentation](https://docs.google.com/presentation/d/1SGgXG--8g3MIUYSZ7tpUUYMgFjnnVVlZ/edit?usp=sharing&ouid=110227914279933022424&rtpof=true&sd=true)
- [Meeting Link](https://us02web.zoom.us/j/83779080423?pwd=WFNHTlQ4Y2lPa0N0aytxVDdJbG9DUT09)
- [Catalyst Incubator](https://docs.google.com/forms/d/e/1FAIpQLSdqjmpu_psFECJWHRJwjSpoh7n-Ttd_WVgghTC8GTCBtsJm6A/viewform)

## Meeting Soundbite:

The townhall's dicussions focused on two areas: the PA/vPA assessment results and and any difficulties the communities are facing with the PA roles; Using the Kenyan elections as a spreing-board for dicussion we election situation in Kenya and used that as a way to explore the role (or not) blockchains can play in helping bring people together, whether in elections or as groups. In the Vietnam room we had two guest speakers Duc Tiger and Nguyen Tran sharing their views on the PA results.

## Breakout Rooms:

0. Welcome
1. Japanese
2. Indonesian
3. English / Eastern Africa
4. Vietnamese

## Run sheet:

1. Welcome
2. Breakout Rooms

## Attendee Numbers:

EHT # | Date | Participants | Japan | Indonesia | Vietnam | English | Korean | Catalyst School
 | -- | -- | -- | -- | -- | -- | -- | -- | -- |
#33 | 13.08.2022 | 51 | 14 | 9 | 25 | 3 | -- | --

## Hosts: 

Hosts, please arrive 30mins before the start of the Townhall to make last-minute adjustments to the schedule and go over the run sheet.

- Yuta Yuta (@cardanoz)
- Mie Tran (@Mietran0407)
- Linh (@Linh-LP)
- Tien Nguyen Anh (@tienna)
- Andreas Sosilo (@andreassosilo) 
- Robert O'Brien (@wolstaeb)
- Angela Gatende (@A-W-G)

## Appologies
- Ayu Kusummaningtyas
- Andy Sibuea (@zicozibu)
- Yan Tirta (@YanTirta)

### Indonesian

Discussion about PA assessment result, vPA aggregate and proposal score (temporary)

### Japan

[**TO BE DONE**]: fill out after the meeting. 

### Vietnam

The meeting last for 2 hours with 2 guest speakers Duc Tiger and Nguyen Tran - 2 Vietnamese PA/vPA - sharing about the PA result and any difficulties the communities are facing with the PA roles.

### English

Just the hosts this time around. However we discussed the election situation in Kenya and used that as a way to explore the role (or not) blockchains can play in helping bring people together, whether in elections or as groups. With such a big topic and freedom to roam, we easily occupied 2 hours.

## Eastern Town Hall Social Media Links
 
- Zoom: https://us02web.zoom.us/j/83779080423?pwd=WFNHTlQ4Y2lPa0N0aytxVDdJbG9DUT09
- Web: https://easterntownhall.com/
- Telegram: https://bit.ly/3H6nEo2
- Discord: https://discord.gg/pnq3CZuUjC
- Twitter: https://bit.ly/3u4EOhZ
- Meetup: https://bit.ly/3H9Xvoo
- Email: [eastern.townhall@gmail.com](mailto:eastern.townhall@gmail.com)

**Comment by andreassosilo** [comment]
### Breakout room Indonesia

- Participants: 9 attendees
- Discussion about PA assessment result, vPA aggregate and proposal score (temporary)

**Comment by Mietran0407** [comment]
**Vietnam breakout room update:**

- Topic: "PA Open Discussion Session"
- Attendees: 25


The meeting last for 2 hours with 2 guest speakers Duc Tiger and Nguyen Tran - 2 Vietnamese PA/vPA - sharing about the PA result and any difficulties the communities are facing with the PA roles.
