### ISSUE TITLE
Event [Townhall]: Eastern Hemisphere Townhall Event #32 - 08 AUG 2022 0900 to 11:00 UTC

### ISSUE THREAD

**Issue by wolstaeb** [C3ETH/c3eth-operations#349]
## Meeting Details:

- Last Meeting: #322  
- Next Meeting: 

- Register for [Eastern Townhall Events](https://bit.ly/3H9Xvoo) via the Cardano and Catalyst Community Network on meetup.com. 
- [Openning Presentation](https://docs.google.com/presentation/d/1SGgXG--8g3MIUYSZ7tpUUYMgFjnnVVlZ/edit?usp=sharing&ouid=110227914279933022424&rtpof=true&sd=true)
- [Meeting Link](https://us02web.zoom.us/j/83779080423?pwd=WFNHTlQ4Y2lPa0N0aytxVDdJbG9DUT09)
- [Catalyst Incubator](https://docs.google.com/forms/d/e/1FAIpQLSdqjmpu_psFECJWHRJwjSpoh7n-Ttd_WVgghTC8GTCBtsJm6A/viewform)

## Meeting Soundbite:

[**TO BE DONE**]: fill out after the meeting. Please see [Breakout Room Summaries below](#breakout-room-summaries)

## Breakout Rooms:

0. Welcome
1. Japanese
2. Indonesian
3. English / Eastern Africa
4. Korean
5. Vietnamese

## Run sheet:

1. Welcome
2. (Programme Item)
3. Breakout Rooms
## Attendee Numbers:

EHT # | Date | Participants | Japan | Indonesia | Vietnam | English | Korean | Catalyst School
| -- | -- | -- | -- | -- | -- | -- | -- | -- |
#32 | 13.08.2022 | 37 | -- | -- | 25 | 3 | -- | --

## Meeting Soundbite:

[**TO BE DONE**]: fill out after the meeting. Please see [Breakout Room Summaries below](#breakout-room-summaries)
## Hosts: 

Hosts, please arrive 30mins before the start of the Townhall to make last-minute adjustments to the schedule and go over the run sheet.

- Yuta Yuta (@cardanoz)
- Mie Tran (@Mietran0407)
- Linh (@Linh-LP)
- Tien Nguyen Anh (@tienna)
- Andreas Sosilo (@andreassosilo) 
- Robert O'Brien (@wolstaeb)
- Angela Gatende (@A-W-G)

## Appologies
- Ayu Kusummaningtyas
- Andy Sibuea (@zicozibu)
- Yan Tirta (@YanTirta)

### Indonesian

[**TO BE DONE**]: fill out after the meeting. 

### Japan

[**TO BE DONE**]: fill out after the meeting. 

### Vietnam

[**TO BE DONE**]: fill out after the meeting. 

### English

[**TO BE DONE**]: fill out after the meeting. 
## Eastern Town Hall Social Media Links
 
- Zoom: https://us02web.zoom.us/j/83779080423?pwd=WFNHTlQ4Y2lPa0N0aytxVDdJbG9DUT09
- Web: https://easterntownhall.com/
- Telegram: https://bit.ly/3H6nEo2
- Discord: https://discord.gg/pnq3CZuUjC
- Twitter: https://bit.ly/3u4EOhZ
- Meetup: https://bit.ly/3H9Xvoo
- Email: [eastern.townhall@gmail.com](mailto:eastern.townhall@gmail.com)

**Comment by Mietran0407** [comment]
Vietnam breakout room update:

**Topic:** "PA Open Discussion Session"
**Attendees**: 25

The meeting last for 2 hours with **2 guest speakers Duc Tiger and Nguyen Tran** - 2 Vietnamese PA/vPA - sharing about the PA result and any difficulties the communities are facing with the PA roles.

**Comment by andreassosilo** [comment]
@Mietran0407 : I think you put it in the wrong issue. This is for 08 August 2022. The one for 13 August 2022 is on the other issue #348

**Comment by Mietran0407** [comment]
Thank you @andreassosilo, As I saw the table said Aug 13, I thought it was this one.

**Comment by wolstaeb** [comment]
@Mietran0407 my screw-up I created two issues for the event. Closing this one.
