### ISSUE TITLE
Operations [Renumeration]: Catalyst School Project Team Payments for SEPT.

### ISSUE THREAD

**Issue by wolstaeb** [C3ETH/c3eth-operations#379]
Perform the payment to project teams handling the operations of the project "[Eastern Catalyst School](https://cardano.ideascale.com/c/idea/405311)" (Proposal ID: 800171) in one transaction for transparency and accountability purposes. 

- [x] Workout the ADA amount received from transaction details
- [x] Work out Ada/Lovelace amounts to be paid.
- [x] [Update Budget and Compensation spreadsheet](https://docs.google.com/spreadsheets/d/194fA-xJHhcEfRxmNd_uVbtyA3X4ABypmkuH16Hox0PY/edit?usp=sharing) with payment details.
- [x] Double Check amounts and put them into payment script
- [x] [Transfer total amount needed](https://explorer.cardano.org/en/address.html?address=stake1uyjftvarnezfl7m30shu3x52kn0drl2lrsppgwxs3xxatjcda4qfn) to the local payment address.
- [x] Update script with input transaction details
- [x] [Perform the Catalyst School Project Team payment](https://explorer.cardano.org/en/transaction?id=876579e35e3d0899fa5c215702df2ab36152646d093349a464855889488f5bdd)
- [x] [Notify the @C3ETH/c3eth-team of the transaction](https://discord.com/channels/868850218995707914/875343499824889947/1022759554343247882).
- [x] Backup payment script details.
- [x] Document transaction details

---
## Transaction Details

Payments are made based on the ADA received from Cardano Catalyst. Links above document the payment plan and the two associated transactions.

![Eastern Townhall Septmember Payments](https://user-images.githubusercontent.com/82072426/191903998-ad2107cb-e122-4b5b-976c-e6c0cb6fd975.png)

For the Catalyst School there is a ₳6,615.22. The remaining is divided three ways for Japan, Indonesian, and Vietnam project teams. These teams will then administer smaller payments to contributors according to their own schedule/plan.

![Catalyst School Team Payments for Septmember](https://user-images.githubusercontent.com/82072426/191904169-00850e7b-efaa-4db2-a9b4-7afb96a8b085.png)

### Notes about payments this time around

1.  Japanese Community payments are held at @cardanoz request. The amount will be paid at a later date.

**Comment by wolstaeb** [comment]
Payment completed.

**Comment by Linh-LP** [comment]
Thanks Robert
