### ISSUE TITLE
Eastern Hemisphere - Strategy Meeting - 13th October 2021 - 0800 to 1020 UTC

### ISSUE THREAD

**Issue by Seomon4u** [C3ETH/c3eth-operations#64]
### Eastern Hemisphere - Strategy Meeting - 13th October 2021 - 0800 to 1020 UTC
- Last Meeting - https://github.com/C3ETH/Catalyst-Eastern-Hemisphere-Co-Ordination/issues/63
- Next Meeting - #65 

### Attendees
Andreas Sosilo - INA - Indonesia
Mie Tran - VN - Vietnam
Tien Nguyen Anh - VN
Robert O'Brien - EN
Tim O'Brien - VN - Vietnam
Paul Ko (KR)
Felix Weber - EN
Stephen Whitenstall - EN
Seomon Blub - EN

Duc Tiger - Vietnam
Yan Tirta - INA - Indonesia
Yuta Yuta - JP - Japan
Greg Bell - EN

#### Further development of ETH

- Use GitHub / CI to refine and automate cohort reporting - Robert
- Partner QA-DAO efforts with ETH on cohort reporting - Stephen
- Support proposers make project websites - Tim
- communicating progress on social channels - Felix, Tim, Stephen
- Entrepreneurial training and development - Business model canvas - Richard
- Rob done is possible to make a short podcast as induction - Linh

### Reporting Infrastructure development 
- **Action** - Identify cohort reporting standards we can automate - Stephen / Robert
- **Action** - Start with an audit of what projects to include  - Stephen / Robert
- **Action** - Identify education needs and partnerships - Stephen 
- Draft is here - https://github.com/C3ETH/Catalyst-Eastern-Hemisphere-Co-Ordination/blob/main/Documentation/Projects/ETH-Infrastructure.md

### What is the purpose of ETH ?
- Lowering the barriers for people to be proposers - Felix
- All ETH proposals fit into this ethos - Robert
- The funds as rewards - treasury or investment ? - Felix
- Possible stakepool setup - Felix
- What if we request additional support from IOG after we receive initial funding ?  - Linh 
- 
### Activities
- **Action** - Respond to email requesting contributions and expected reward by next Monday 18th October 2021 - Felix

### Communication Issues
- Come up with a plan to communicate ETH to local communities - Link
- It is the responsibility of each group to organize ETH marketing - local communities have the best knowledge of how to do this - Felix

**Comment by FelixfromSwarm** [comment]
[meeting_saved_chat.txt](https://github.com/C3ETH/Catalyst-Eastern-Hemisphere-Co-Ordination/files/7337356/meeting_saved_chat.txt)
