### ISSUE TITLE
Eastern Hemisphere Townhall Meeting - 20th Nov 0800 to 0900 UTC

### ISSUE THREAD

**Issue by wolstaeb** [C3ETH/c3eth-operations#85]
- Last Meeting: #78 
- Next Meeting: 
- **[Meeting Link](https://www.meetup.com/Cardano-Catalyst-Community-Network/events/282029062)**

## Meeting Soundbite

[**TO BE DONE**]: fill out after the meeting. Please see [Breakout Room Summaries below](#breakout-room-summaries)

## Breakout Rooms

0. Welcome
1. Japanese
2. Indonesian 
3. English / Eastern Africa
4. Vietnamese
5. Catalyst School

## Run sheet

1. Welcome
2. Eastern Africa Welcome
3. Breakout Rooms

## Attendees

EHT # | Date | Participants | Japan | Indonesia | Vietnam | English | Korean | Catalyst School
-- | -- | -- | -- | -- | -- | -- | -- | --
1 | 29/07/2021 | 47 | 15 | 14 | 5 | 7 | - | -
2 | 05/08/2021 | 64 | 11 | 11 | 32 | 12 | - | -
3 | 12/08/2021 | 93 | 43 | 10 | 29 | 11 | - | -
4 | 19/08/2021 | 94 | 49 | 3 | 19 | 11 | - | 12
5 | 26/08/2021 | 62 | 35 | 7 | 10 | 10 | - | -
6 | 02/09/2021 | 76 | 31 | 6 | 22 | 14 | - | 3
7 | 09/09/2021 | 95 | 39 | 9 | 30 | 7 | 4 | 6
8 | 18/09/2021 | 95 | 39 | 8 | 31 | 7 | 4 | 6
9 | 25/09/2021 | 72 | 25 | 8 | 24 | 12 | 3 | -
10 | 02/10/2021 | 85 | 40 | 11 | 22 | 8 | 4 | -
11 | 9/10/2021 | 47 | 26 | 10 | 3 | 8 | - | -
12 | 16/10/2021 | 69 | 21 | - | 41 | 5 | 2 | -
13 | 23/10/2021 |48 | 16 | 3 | 11 | 8 | - | -
14 | 06/11/2021 |- | - | - | 9  | - | - | -
15 | 06/11/2021 | 68 | 25 | 4 | 14 | 20 | - | 5

## Hosts

Hosts, please arrive 30mins before the start of the Townhall to make last-minute adjustments to the schedule and go over the run sheet.

- Yan Tirta (@YanTirta)  - INA 
- Mie Tran (@Mietran0407) - VN
- Yuta Yuta (@cardanoz) - JP - JP
- Robert O'Brien  (@wolstaeb) - EN 
- Angela Gatende (@A-W-G) - EN
- Felix Weber (@FelixfromSwarm) - EN 
- Andreas Sosilo (@andreassosilo) - IN
- Stephen Whitenstall (@stephen-rowan) - EN
- Linh LP - VN/EN
- Seomon Blub  (@Seomon4u) - EN 

### Indonesian

 Indonesian Breakout room has 4 members joining today. We discuss about Fund 7 & management for Cardano Indonesia Community. From Indonesia we have 4 submitted draft proposal in IdeaScale.

### Japan

[**TO BE DONE**]: fill out after the meeting. 

### Vietnam

Vietnam Breakout room has 14 members joining today. We share information, timeline, challenges for Fund7 and motivate people to join. Expect around 15 proposals submitted to this fund. Thank you so much

### English

[**TO BE DONE**]: fill out after the meeting. 

[Video](https://youtu.be/ymytQdyh-j0)

## Eastern Town Hall Social Media Links
 
- Meetup: https://www.meetup.com/Cardano-Catalyst-Community-Network/
- Telegram: https://t.me/joinchat/ODKTOvGnrHEwNTc6
- Discord: https://discord.gg/6T825EyvrG
- Email: eastern.townhall@gmail.com

## Town Hall Social Media Links

- [Project Catalyst Fund 7 Townhall #2 Nov 20](https://www.youtube.com/watch?v=nP0r5KwNtQk) and [Slides](https://docs.google.com/presentation/d/1NG5Xa1BBMiNBN1NsptR02GSN5tae3RVVA9l4NEbRalY/edit)
- **[Recurring Registration link]( https://bit.ly/3rCicSR)**, add to your calendars and just simply join each week using the same access.

Fund6 Feedback Form: https://forms.gle/7FYP2MRaGrVDAUh87

Official proposer guide: https://bit.ly/3AX2sxf  by Anthony

**Comment by Mietran0407** [comment]
Vietnam Breakout room has 14 members joining today. We share information, timeline, challenges for Fund7 and motivate people to join. Expect around 15 proposals submitted to this fund. Thank you so much

**Comment by andreassosilo** [comment]
@wolstaeb :  Indonesian Breakout room has 4 members joining today. We discuss about Fund 7 & management for Cardano Indonesia Community. From Indonesia we have 4 submitted draft proposal in IdeaScale.
