### ISSUE TITLE
Eastern Hemisphere Meeting - 4th Dec 0800 to 0900 UTC 

### ISSUE THREAD

**Issue by wolstaeb** [C3ETH/c3eth-operations#90]
- Last Meeting: #85 
- Next Meeting: #92 

**[Meeting Link](https://us02web.zoom.us/meeting/register/tZAufuCtrD0uGNVVt0StWL2cZtCwvWhkza2a)**

## Meeting Soundbite

[**TO BE DONE**]: fill out after the meeting. Please see [Breakout Room Summaries below](#breakout-room-summaries)

## Breakout Rooms

0. Welcome
1. Japanese
2. Indonesian 
3. English / Eastern Africa
4. Vietnamese

## Run sheet

1. Welcome
2. Eastern Africa Welcome
3. Breakout Rooms

## Attendees

EHT # | Date | Participants | Japan | Indonesia | Vietnam | English | Korean | Catalyst School
-- | -- | -- | -- | -- | -- | -- | -- | --
1 | 29/07/2021 | 47 | 15 | 14 | 5 | 7 | - | -
2 | 05/08/2021 | 64 | 11 | 11 | 32 | 12 | - | -
3 | 12/08/2021 | 93 | 43 | 10 | 29 | 11 | - | -
4 | 19/08/2021 | 94 | 49 | 3 | 19 | 11 | - | 12
5 | 26/08/2021 | 62 | 35 | 7 | 10 | 10 | - | -
6 | 02/09/2021 | 76 | 31 | 6 | 22 | 14 | - | 3
7 | 09/09/2021 | 95 | 39 | 9 | 30 | 7 | 4 | 6
8 | 18/09/2021 | 95 | 39 | 8 | 31 | 7 | 4 | 6
9 | 25/09/2021 | 72 | 25 | 8 | 24 | 12 | 3 | -
10 | 02/10/2021 | 85 | 40 | 11 | 22 | 8 | 4 | -
11 | 9/10/2021 | 47 | 26 | 10 | 3 | 8 | - | -
12 | 16/10/2021 | 69 | 21 | - | 41 | 5 | 2 | -
13 | 23/10/2021 |48 | 16 | 3 | 11 | 8 | - | -
14 | 06/11/2021 |- | - | - | 9  | - | - | -
15 | 06/11/2021 | 68 | 25 | 4 | 14 | 20 | - | 5
16 | 04/12/2021 |- | - | - | -  | - | - | -

## Hosts

Hosts, please arrive 30mins before the start of the Townhall to make last-minute adjustments to the schedule and go over the run sheet.

- Yan Tirta (@YanTirta)  - INA 
- Mie Tran (@Mietran0407) - VN
- Yuta Yuta (@cardanoz) - JP - JP
- Robert O'Brien  (@wolstaeb) - EN 
- Angela Gatende (@A-W-G) - EN
- Felix Weber (@FelixfromSwarm) - EN 
- Andreas Sosilo (@andreassosilo) - IN
- Stephen Whitenstall (@stephen-rowan) - EN
- Linh LP - VN/EN
- Seomon Blub  (@Seomon4u) - EN 
- Pau Ko (@haskellcoding29 ) -KO
- Stephen Whitenstall (@stephen-rowan) - EN

### Indonesian

[**TO BE DONE**]: fill out after the meeting. 
### Japan

[**TO BE DONE**]: fill out after the meeting. 
### Vietnam

[**TO BE DONE**]: fill out after the meeting. 
### Korea

[**TO BE DONE**]: fill out after the meeting. 
### English

[**TO BE DONE**]: fill out after the meeting. 

## Eastern Town Hall Social Media Links
 
- Zoom: https://tinyurl.com/Eastern-Townhall-Zoom
- Telegram: https://t.me/joinchat/ODKTOvGnrHEwNTc6
- Discord: https://discord.gg/6T825EyvrG
- Email: eastern.townhall@gmail.com

## Town Hall Social Media Links

**Recurring Registration link**: https://bit.ly/3rCicSR add to your calendars and just simply join each week using the same access.

**Fund6 Challenges Overview**: https://www.youtube.com/watch?v=crs3lVaGejY&t=1821s

Fund6 Feedback Form: https://forms.gle/7FYP2MRaGrVDAUh87

Official proposer guide: https://bit.ly/3AX2sxf  by Anthony

**Comment by andreassosilo** [comment]
**From Indonesia Breakout Room:**

- Total: 2 hours discussion
- We have around 7-8 active participants this time
- Having discussion about Catalyst in general for newcomer
- Discussion about Community Advisor work in Fund 7
- Giving examples on how to use CA Tools and how to use IdeaScale
- Show Fund 6 example of CA review and vCA review
- Q&A

**Comment by Mietran0407** [comment]
Vietnam breakout room has 3 people joining with no new members coming to this meeting. This might be because people know about the timeline with weekly updated information, they have not yet anything to share or questions to bring up. Looking forward to the next Ideafest which might take place on Dec 19th. Thank you.
